---
- name: Export the kubeconfig
  ansible.builtin.command:
    argv:
      - kops
      - export
      - --name
      - "{{ cluster_name }}"
      - kubecfg
      - --admin
      - --state
      - "{{ state_store }}"
      - --kubeconfig
      - /tmp/head-cluster.yaml
  register: export_kops_output
  changed_when: export_kops_output.rc == 0

- name: Install AWX operator
  kubernetes.core.helm:
    chart_ref: awx-operator
    chart_repo_url: https://ansible-community.github.io/awx-operator-helm
    chart_version: 3.1.0
    create_namespace: true
    kubeconfig: /tmp/head-cluster.yaml
    release_name: awx-operator
    release_namespace: awx
    release_state: present
    timeout: 10m0s
    wait: true
  tags:
    - awx_setup

- name: Install AWX
  kubernetes.core.k8s:
    kubeconfig: /tmp/head-cluster.yaml
    resource_definition:
      apiVersion: awx.ansible.com/v1beta1
      kind: AWX
      metadata:
        name: awx-deployment
        namespace: awx
      spec:
        service_type: loadbalancer
        postgres_data_volume_init: true
        postgres_init_container_commands: |
          chown 26:0 /var/lib/pgsql/data
          chmod 700 /var/lib/pgsql/data
    state: present

# Add waits
