---
- name: Set variables
  ansible.builtin.set_fact:
    runner_cluster_names: |
      {{
        [awx_stack.name_prefix + "-runner"] |
        product(range(1, awx_stack.runners.count + 1) | map('string')) |
        map('join', '-') |
        zip_longest([], fillvalue=awx_cluster.nodes.worker.instance_type + "-aws.k8s.local") |
        map('join', '-')
      }}
    state_store: s3://{{ awx_cluster.s3.bucket_name }}
  tags:
    - always

- name: Retrieve list of clusters
  ansible.builtin.command:
    argv:
      - kops
      - get
      - clusters
      - --output
      - json
      - --state
      - "{{ state_store }}"
  register: clusters_output
  changed_when: false
  ignore_errors: true
  tags:
    - always

- name: Parse cluster names
  ansible.builtin.set_fact:
    existing_cluster_names: |
      {{
        clusters_output.stdout |
        from_json |
        community.general.json_query('[*].metadata.name')
      }}
  tags:
    - always
  when:
    - clusters_output.rc == 0

- name: Import asynchronous AWX stack runner creation tasks
  ansible.builtin.import_tasks:
    file: create_runners_async.yaml
  vars:
    cluster_names: "{{ runner_cluster_names | difference(existing_cluster_names | default([])) }}"
  tags:
    - create

- name: Import asynchronous AWX stack runner deletion tasks
  ansible.builtin.import_tasks:
    file: delete_runners_async.yaml
  vars:
    cluster_names: "{{ existing_cluster_names | default([]) | intersect(runner_cluster_names) }}"
  tags:
    - delete

- name: Import KOps role for head cluster management
  ansible.builtin.import_role:
    name: kops
  vars:
    kops_cluster: "{{ awx_cluster }}"
    kops_full_cluster_name_override: "{{ awx_stack.name_prefix }}-head-{{ awx_cluster.nodes.worker.instance_type }}-aws.k8s.local"
