---
- name: Build a goal descriptioin
  hosts: localhost
  vars_files:
    - ./vars.yaml
  vars:
    path_to_output: /tmp/goal.json
  pre_tasks:
    - include_tasks: ../tasks/precondition_setup.yml
  tasks:
  - name: Load info.json
    set_fact:
      info_content: "{{ lookup('file', '../info.json') | from_json }}"

  - name: Build the goal description
    set_fact:
      goal_object:
        goal: |
          I would like to check if the following condition is satisfiled, given a Kubernetes cluster with `kubeconfig.yaml`
              {{ info_content.goal }}

          To check the condition, do the following steps. 
          - deploy a Kyverno policy to the cluster
          - chcek if the policy is correctly deployed. 

          If deploying the policy failed and if you can fix the issue, you will do it and try deploying again.
          Once you get a final answer, you can quit the work.

          The cluster's kubeconfig is at `{% raw %}{{ kubeconfig }}{% endraw %}`.
        vars:
          kubeconfig: "{{ lookup('file', agent_kubeconfig) }}"
  - name: Write the goal description to JSON file
    copy:
      content: "{{ goal_object | to_json }}"
      dest: "{{ path_to_output }}"