---
- name: Documenting Incident #1
  set_fact:
    all_incidents: "{{ all_incidents + [ docs_incident_1 ] }}"
  tags: documentation, incident_1

- name: fault_injection_incident_1
  ansible.builtin.import_role:
    name: fault_injection
  vars:
      is_native: true
      is_injection: true
  tags: incident_1
  when: is_fault_injection | bool

- name: fault_removal_incident_1
  ansible.builtin.import_role:
    name: fault_removal
  vars:
      is_native: true
      is_removal: true
  tags: incident_1
  when: is_fault_removal | bool
