---
- name: Value Check
  ansible.builtin.debug:
    msg: load-generator
  when: is_fault_injection and is_otel_astronomy_shop_dynamic_load

- name: Add dynamic load variables to the loadgenerator container
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    name: load-generator
    namespace: "{{ otel_astronomy_app_namespace_project_name }}"
    kubeconfig: "{{ kubeconfig }}"
    state: present
    wait: true
    resource_definition:
      spec:
        template:
          spec:
            containers:
              - name: load-generator  # Ensure this matches the container name in the deployment
                env: "{{ dynamic_load_vars }}"
  when: is_fault_injection and is_otel_astronomy_shop_dynamic_load
