---
- name: Document this fault injection
  set_fact:
    injection_docs: "{{ injection_docs | default([]) + [curr_docs] }}"
  vars:
    curr_docs:
      name: "Authentication Distruption"
      author: "@JacksonArthurClark"
      description: "Valkey Authentication Disruption by setting invalid password"
      application: "otel_astronomy_shop"
      fault_type: "Custom"
      required_fields:
        - "target_namespace_name"
        - "valkey_pod_name"
        - "target_service"
  tags:
    - injection_docs

- name: Get the valkey pod name
  ansible.builtin.shell: |
    KUBECONFIG={{ kubeconfig }} kubectl get pods -n {{ target_namespace_name }} -l app.kubernetes.io/component=valkey -o jsonpath='{.items[0].metadata.name}'
  register: valkey_pod_name
  when:
    - is_custom
    - is_fault_injection or is_fault_removal
    - is_valkey_auth_disruption

- name: Print valkey pod name (for debugging)
  debug:
    var: valkey_pod_name.stdout
  when:
    - is_custom
    - is_fault_injection or is_fault_removal
    - is_valkey_auth_disruption

- name: Set invalid password in valkey
  ansible.builtin.shell: |
    KUBECONFIG={{ kubeconfig }} kubectl exec -n {{ target_namespace_name }} {{ valkey_pod_name.stdout }} -- valkey-cli CONFIG SET requirepass "invalid_pass"
  register: set_invalid_pass_result
  when:
    - is_custom
    - is_fault_injection
    - is_valkey_auth_disruption

- name: Remove valkey password to recover access
  ansible.builtin.shell: |
    KUBECONFIG={{ kubeconfig }} kubectl exec -n {{ target_namespace_name }} {{ valkey_pod_name.stdout }} -- valkey-cli CONFIG SET requirepass ""
  register: remove_pass_result
  when:
    - is_custom
    - is_fault_removal
    - is_valkey_auth_disruption

- name: Verify invalid password set in valkey
  ansible.builtin.shell: |
    KUBECONFIG={{ kubeconfig }} kubectl exec -n {{ target_namespace_name }} {{ valkey_pod_name.stdout }} -- valkey-cli CONFIG GET requirepass
  register: verify_pass_addition_result
  ignore_errors: yes
  when:
    - is_custom
    - is_fault_injection
    - is_valkey_auth_disruption

- name: Verify password removal in valkey
  ansible.builtin.shell: |
    KUBECONFIG={{ kubeconfig }} kubectl exec -n {{ target_namespace_name }} {{ valkey_pod_name.stdout }} -- valkey-cli CONFIG GET requirepass
  register: verify_pass_removal_result
  when:
    - is_custom
    - is_fault_removal
    - is_valkey_auth_disruption

- name: Print addition verification result
  debug:
    var: verify_pass_addition_result.stdout
  when:
    - is_custom
    - is_fault_injection
    - is_valkey_auth_disruption

- name: Print removal verification result
  debug:
    var: verify_pass_removal_result.stdout
  when:
    - is_custom
    - is_fault_removal
    - is_valkey_auth_disruption

- name: Restart relevant service interacting with the valkey component
  ansible.builtin.shell: |
    KUBECONFIG={{ kubeconfig }} kubectl delete pod -l app.kubernetes.io/name={{ target_service }} -n {{ target_namespace_name }}
  register: service_restart
  ignore_errors: yes
  when:
    - is_custom
    - is_fault_injection or is_fault_removal
    - is_valkey_auth_disruption

- name: Print service restart result
  debug:
    var: service_restart
  when:
    - is_custom
    - is_fault_injection or is_fault_removal
    - is_valkey_auth_disruption
