- name: Document this fault injection
  set_fact:
    injection_docs: "{{ injection_docs | default([]) + [curr_docs] }}"
  vars:
    curr_docs:
      name: "Scale Replicas"
      author: "@JacksonArthurClark"
      description: "Scale replicaset of target service to target replicas"
      application: "otel_astronomy_shop"
      fault_type: "Custom"
      required_fields:
        - "target_namespace_name"
        - "target_replicas"
        - "target_deployments"
  tags:
    - injection_docs

- name: Scale deployment to target replicas
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: apps/v1
    kind: Deployment
    name: "{{ item }}"
    namespace: "{{ target_namespace_name }}"
    resource_definition:
      spec:
        replicas: "{{ target_replicas }}"
  loop: "{{ target_deployments }}"
  register: result
  when: is_custom and is_scale_deployments
  
- name: Print scale down result (for debugging)
  debug:
    var: result
  when: is_custom and is_scale_deployments
