- name: Document this fault injection
  set_fact:
    injection_docs: "{{ injection_docs | default([]) + [curr_docs] }}"
  vars:
    curr_docs:
      name: "Chaos Network Delay"
      author: "@divyapathak24"
      description: "Create networkchaos of 20 seconds for request/responses in the network connections of the ProductCatalogService"
      fault_type: "ChaosMesh"
      required_fields:
        - "chaos_mesh_namespace_project_name"
        - "target_label_name1"
        - "target_namespace_name"
  tags:
    - injection_docs

- name: Inject network delay chaos leveraging the Chaos framework
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: chaos-mesh.org/v1alpha1
      kind: Schedule
      metadata:
        name: "schedule-networkdelay-{{ target_namespace_name }}-{{ target_label_name1 }}"
        namespace: "{{ chaos_mesh_namespace_project_name }}"
      spec:
        schedule: "* * * * *"
        historyLimit: 1
        concurrencyPolicy: "Forbid"
        type: "NetworkChaos"
        networkChaos:
          action: delay
          mode: all
          selector:
            namespaces:
              - "{{ target_namespace_name }}"
            labelSelectors:
              "app.kubernetes.io/component": "{{ target_label_name1 }}"
          delay:
            latency: "20000ms"
          duration: "55s"
  register: fault_injection_status
  tags: chaos_mesh
  when: is_network_delay_chaos and is_fault_injection

- name: Remove network delay chaos leveraging the Chaos framework
  kubernetes.core.k8s:
    state: absent
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: chaos-mesh.org/v1alpha1
      kind: Schedule
      metadata:
        name: "schedule-networkdelay-{{ target_namespace_name }}-{{ target_label_name1 }}"
        namespace: "{{ chaos_mesh_namespace_project_name }}"
  register: fault_removal_status
  tags: chaos_mesh
  when: is_network_delay_chaos and is_fault_removal
