---
- name: Document this fault injection
  set_fact:
    injection_docs: "{{ injection_docs | default([]) + [curr_docs] }}"
  vars:
    curr_docs:
      name: "Chaos Pod Unavailable"
      author: "@divyapathak24"
      description: "Makes the checkoutService pod unavailable"
      fault_type: "ChaosMesh"
      required_fields:
        - "chaos_mesh_namespace_project_name"
        - "target_label_name1"
        - "target_namespace_name"
  tags:
    - injection_docs

- name: Inject pod chaos leveraging the Chaos framework
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: chaos-mesh.org/v1alpha1
      kind: Schedule
      metadata:
        name: "schedule-podchaos-{{ target_namespace_name }}-{{ target_label_name1 }}"
        namespace: "{{ tools_helm_releases.chaos_mesh.namespace }}"
      spec:
        schedule: "* * * * *"
        historyLimit: 1
        concurrencyPolicy: "Forbid"
        type: "PodChaos"
        podChaos:
          action: pod-failure
          mode: all
          selector:
            namespaces:
                - "{{ target_namespace_name }}"
            labelSelectors:
              "app.kubernetes.io/component": "{{ target_label_name1 }}"
          duration: "55s"
  register: fault_injection_status
  tags: chaos_mesh
  when: is_pod_chaos and is_fault_injection

- name: Remove pod chaos leveraging the Chaos framework
  kubernetes.core.k8s:
    state: absent
    kubeconfig: "{{ kubeconfig }}"
    definition:
      apiVersion: chaos-mesh.org/v1alpha1
      kind: Schedule
      metadata:
        name: "schedule-podchaos-{{ target_namespace_name }}-{{ target_label_name1 }}"
        namespace: "{{ tools_helm_releases.chaos_mesh.namespace }}"
  register: fault_removal_status
  tags: chaos_mesh
  when: is_pod_chaos and is_fault_removal
