version: 2
updates:
  - package-ecosystem: "github-actions"
    directories:
      - "/"
    groups:
      actions-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"

  - package-ecosystem: "docker"
    directories:
      - "ciso/"
      - "sre/tools/kubernetes-topology-mapper/"
    groups:
      docker-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: daily

  - package-ecosystem: "gomod"
    directories:
      - "sre/local_cluster/"
    groups:
      go-production-dependencies:
        dependency-type: "production"
    schedule:
      interval: "daily"

  - package-ecosystem: "pip"
    directories:
      - "/"
      - "sre/"
      - "sre/tools/**/"
      - "sre/remote_cluster/"
    groups:
      pip-production-dependencies:
        dependency-type: "production"
      pip-development-dependencies:
        dependency-type: "development"
        exclude-patterns:
          - elasticsearch
    schedule:
      interval: "daily"
