version: 2
updates:
  - package-ecosystem: docker
    directories:
      - sre/tools/**/*
    groups:
      docker-images-production:
        applies-to: version-updates
    schedule:
      interval: daily
