version: 2
updates:
  - package-ecosystem: github-actions
    directories:
      - /
    schedule:
      interval: daily

  - package-ecosystem: docker
    directories:
      - sre/tools/death-star-bench-*/
      - sre/tools/kubernetes-topology-mapper/
      - sre/tools/elasticsearch-dummy-app/
      - ciso/
    schedule:
      interval: weekly

  - package-ecosystem: gomod
    directories:
      - sre/local_cluster/
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directories:
      - /
      - sre/remote_cluster/
    schedule:
      interval: weekly

  - package-ecosystem: pip
    directories:
      - sre/
      - sre/tools/**/
    schedule:
      interval: daily
    open-pull-requests-limit: 0
