check_violations:
  - policy_name: "container-security-controls"
    resource:
      name: "test-untrusted-registry"
      namespace: "paa"
      kind: "Pod"
      api_version: "v1"
    expected_result: fail

check_unchanged_policies:
  - policy_name: "service-account-requirements"
