- uid: bec6633tzlwqod
  title: Request latency is too high
  condition: C
  data:
    - refId: A
      relativeTimeRange:
        from: 120
        to: 0
      datasourceUid: prometheus
      model:
        datasource:
          type: prometheus
          uid: prometheus
        editorMode: code
        expr: histogram_quantile(0.95, sum by(le, service_name, namespace) (rate(traces_span_metrics_duration_milliseconds_bucket{service_name!~"flagd|otel-demo-loadgenerator"}[2m])))
        instant: true
        intervalMs: 1000
        legendFormat: __auto
        maxDataPoints: 43200
        range: false
        refId: A
    - refId: B
      relativeTimeRange:
        from: 120
        to: 0
      datasourceUid: __expr__
      model:
        conditions:
          - evaluator:
              params: []
              type: gt
            operator:
              type: and
            query:
              params:
                - B
            reducer:
              params: []
              type: last
            type: query
        datasource:
          type: __expr__
          uid: __expr__
        expression: A
        intervalMs: 1000
        maxDataPoints: 43200
        reducer: last
        refId: B
        settings:
            mode: dropNN
        type: reduce
    - refId: C
      relativeTimeRange:
        from: 120
        to: 0
      datasourceUid: __expr__
      model:
        conditions:
          - evaluator:
              params:
                - 1500
              type: gt
            operator:
              type: and
            query:
              params:
                - C
            reducer:
              params: []
              type: last
            type: query
        datasource:
            type: __expr__
            uid: __expr__
        expression: B
        intervalMs: 1000
        maxDataPoints: 43200
        refId: C
        type: threshold
  noDataState: OK
  execErrState: OK
  for: 1m
  annotations:
    description: 'Latency in service {{ $labels.service_name }} in namespace {{ $labels.namespace }} is above 1500s (current value: {{ $values.C.Value }}s)'
    summary: High latency detected in service {{ $labels.service_name }} in namespace {{ $labels.namespace }}.
  isPaused: false
  notification_settings:
    receiver: grafana-default-email
- uid: cec6cs6qqkphcd
  title: Request error rate is high
  condition: C
  data:
    - refId: A
      relativeTimeRange:
        from: 120
        to: 0
      datasourceUid: prometheus
      model:
        datasource:
          type: prometheus
          uid: prometheus
        editorMode: code
        expr: sum by (service_name, namespace) (delta(traces_span_metrics_calls_total{status_code="STATUS_CODE_ERROR", service_name!~"flagd|otel-demo-loadgenerator"}[2m]))
        instant: true
        intervalMs: 1000
        legendFormat: __auto
        maxDataPoints: 43200
        range: false
        refId: A
    - refId: B
      relativeTimeRange:
        from: 120
        to: 0
      datasourceUid: __expr__
      model:
        conditions:
          - evaluator:
              params: []
              type: gt
            operator:
              type: and
            query:
              params:
                - B
            reducer:
              params: []
              type: last
            type: query
        datasource:
          type: __expr__
          uid: __expr__
        expression: A
        intervalMs: 1000
        maxDataPoints: 43200
        reducer: last
        refId: B
        settings:
            mode: dropNN
        type: reduce
    - refId: C
      relativeTimeRange:
        from: 120
        to: 0
      datasourceUid: __expr__
      model:
        conditions:
          - evaluator:
              params:
                - 0
              type: gt
            operator:
              type: and
            query:
              params:
                - C
            reducer:
              params: []
              type: last
            type: query
        datasource:
          type: __expr__
          uid: __expr__
        expression: B
        intervalMs: 1000
        maxDataPoints: 43200
        refId: C
        type: threshold
  noDataState: OK
  execErrState: OK
  for: 1m
  annotations:
    description: 'Request error rate in service {{ $labels.service_name }} in namespace {{ $labels.namespace }} is above 0 (current value: {{ $values.C.Value }})'
    summary: Error rate is too high for service {{ $labels.service_name }} in namespace {{ $labels.namespace }}.
  isPaused: false
  notification_settings:
    receiver: grafana-default-email
