- uid: eec5y4zd03ny8d
  title: Kafka has a high connection closure rate
  condition: C
  data:
    - refId: A
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: prometheus
      model:
        datasource:
          type: prometheus
          uid: prometheus
        editorMode: code
        expr: sum by (job) (kafka_consumer_connection_close_rate)
        instant: true
        intervalMs: 1000
        legendFormat: __auto
        maxDataPoints: 43200
        range: false
        refId: A
    - refId: B
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: __expr__
      model:
        conditions:
          - evaluator:
              params: []
              type: gt
            operator:
              type: and
            query:
              params:
                - B
            reducer:
              params: []
              type: last
            type: query
        datasource:
          type: __expr__
          uid: __expr__
        expression: A
        intervalMs: 1000
        maxDataPoints: 43200
        reducer: count
        refId: B
        settings:
            mode: dropNN
        type: reduce
    - refId: C
      relativeTimeRange:
        from: 600
        to: 0
      datasourceUid: __expr__
      model:
        conditions:
          - evaluator:
              params:
                - 0
              type: gt
            operator:
              type: and
            query:
              params:
                - C
            reducer:
              params: []
              type: last
            type: query
        datasource:
          type: __expr__
          uid: __expr__
        expression: B
        intervalMs: 1000
        maxDataPoints: 43200
        refId: C
        type: threshold
  noDataState: OK
  execErrState: OK
  for: 1m
  annotations:
    description: 'Job {{ $labels.job }} has a high closure rate above 0 (current value: {{ $values.C.Value }})'
    summary: High connection closure rate detected in job {{ $labels.job }}
  labels: {}
  isPaused: false
  notification_settings:
    receiver: grafana-default-email
