---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: it-bench-restrictive-scc
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
defaultAddCapabilities: []
requiredDropCapabilities:
  - ALL
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seccompProfiles:
  - 'runtime/default'
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: it-bench-allow-host-capabilities-scc
allowPrivilegedContainer: false
readOnlyRootFilesystem: false
allowedCapabilities:
  - NET_BIND_SERVICE
defaultAddCapabilities: []
requiredDropCapabilities:
  - ALL
runAsUser:
  type: MustRunAsNonRoot
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
allowHostDirVolumePlugin: true
allowHostNetwork: true
allowHostPorts: true
allowHostPID: true
seccompProfiles:
  - 'runtime/default'
---
apiVersion: security.openshift.io/v1
kind: SecurityContextConstraints
metadata:
  name: it-bench-allow-priveleged-container-scc
allowPrivilegedContainer: true
readOnlyRootFilesystem: false
defaultAddCapabilities: []
requiredDropCapabilities:
  - ALL
runAsUser:
  type: RunAsAny
seLinuxContext:
  type: RunAsAny
fsGroup:
  type: RunAsAny
supplementalGroups:
  type: RunAsAny
seccompProfiles:
  - 'runtime/default'
