---
- name: Inject Chaos Mesh fault
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ chaos_mesh_namespace_project_name }}"
    resource_definition: "{{ spec.chaos['resource_definition.yaml'] | from_yaml }}"
  tags:
    - fault_injection

- name: Remove Chaos Mesh fault
  kubernetes.core.k8s:
    state: absent
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ chaos_mesh_namespace_project_name }}"
    resource_definition: "{{ spec.chaos['resource_definition.yaml'] | from_yaml }}"
  tags:
    - fault_removal
