---
- name: Injecting Unsupported Image Fault
  kubernetes.core.k8s_json_patch:
    api_version: apps/v1
    kind: Deployment
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ spec.custom.target.deployment.name }}"
    namespace: "{{ spec.custom.target.deployment.namespace }}"
    patch:
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: quay.io/felix_george/checkout_service:latest
  tags:
    - fault_injection

- name: Removing Unsupported Image Fault
  kubernetes.core.k8s_rollback:
    api_version: apps/v1
    kind: Deployment
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ spec.custom.target.deployment.name }}"
    namespace: "{{ spec.custom.target.deployment.namespace }}"
  tags:
    - fault_removal
