---
- name: Run the Kubernetes Job for Elasticsearch Dummy App
  kubernetes.core.k8s:
    api_version: batch/v1
    kind: Job
    name: es-dummy-app
    namespace: "{{ spec.elasticsearch.cluster_namespace }}"
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      spec:
        template:
          metadata:
            labels:
              app: es-dummy-app
          spec:
            restartPolicy: Never
            containers:
            - name: es-dummy-app
              image: yinfangchen/es-dummy-app:latest
              env:
              - name: ES_HOST
                value: "https://elasticsearch-master:9200"
              - name: ES_USER
                valueFrom:
                  secretKeyRef:
                    name: elasticsearch-master-credentials
                    key: username
              - name: ES_PASS
                value: "changeme" # default wrong password
  tags:
    - fault_injection

- name: Delete existing Elasticsearch Dummy App Job (if exists)
  kubernetes.core.k8s:
    api_version: batch/v1
    kind: Job
    name: es-dummy-app
    namespace: "{{ spec.elasticsearch.cluster_namespace }}"
    kubeconfig: "{{ kubeconfig }}"
    state: absent
    wait: true
  tags:
    - fault_removal

- name: Get all job pods
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ spec.elasticsearch.cluster_namespace }}"
    kubeconfig: "{{ kubeconfig }}"
    label_selectors:
      - job-name=es-dummy-app
  register: job_pods_info
  tags:
    - fault_removal

- name: Delete all job pods
  kubernetes.core.k8s:
    kind: Pod
    name: "{{ item.metadata.name }}"
    namespace: "{{ spec.elasticsearch.cluster_namespace }}"
    kubeconfig: "{{ kubeconfig }}"
    state: absent
    wait: true
  loop: "{{ job_pods_info.resources }}"
  tags:
    - fault_removal
