---
- ansible.builtin.import_tasks: collect_documentation.yaml
- ansible.builtin.import_tasks: create_scenario_records.yaml
- ansible.builtin.import_tasks: create_ground_truth_records.yaml
- ansible.builtin.import_tasks: collect_fault_injection_docs.yaml
