---
# ToDo: Ingress-URL to be brought in from the common role
- name: Check availability of ports
  ansible.builtin.shell: |
    lsof -i :{{ item }} > /dev/null && echo "in_use" || echo "available"
  register: lsof_check
  loop: "{{ range(32100, 32125) | list }}"
  changed_when: false
  failed_when: false
  loop_control:
    loop_var: item

- name: Assign a dynamic port if one is available
  ansible.builtin.set_fact:
    dynamic_port: "{{ (lsof_check.results | selectattr('stdout', 'equalto', 'available') | map(attribute='item') | list | first) }}"

- name: Kubectl port-forward on/for OpenSearch service with dynamic port
  ansible.builtin.command: >
    kubectl -n {{ helm_release.namespace }} port-forward svc/opensearch-cluster-master {{ dynamic_port }}:9200 --request-timeout=10m
  environment:
    KUBECONFIG: "{{ tools_cluster.kubeconfig }}"
  async: 600
  poll: 0
  changed_when: false

- name: Wait for port-forward to be available
  ansible.builtin.wait_for_connection:
    delay: 5
    timeout: 30

- name: Delete OpenSearch indices
  ansible.builtin.uri:
    url: "http://127.0.0.1:{{ dynamic_port }}/{{ item }}"
    method: DELETE
    status_code: [200, 404]
  loop:
    - "otel"
    - "jaeger-service-*"
    - "jaeger-span-*"
    - "top_queries-*"
