---
- name: Delete events across namespaces
  ansible.builtin.command: "kubectl delete events --all"
  environment:
    KUBECONFIG: "{{ tools_cluster.kubeconfig }}"
  register: delete_events_result
  changed_when: "'deleted' in delete_events_result.stdout"
  failed_when: false
