---
- name: Scale down Prometheus and Prometheus-related statefulsets to reset data
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    api_version: apps/v1
    kind: StatefulSet
    name: "{{ item }}"
    namespace: "{{ helm_release.namespace }}"
    resource_definition:
      spec:
        replicas: 0
    wait: true
  loop:
    - "alertmanager-prometheus-kube-prometheus-alertmanager"
    - "prometheus-prometheus-kube-prometheus-prometheus"
  when:
    - tools_cluster.platform == "kubernetes"

# # NOTE: Not needed as installation triggers scale up
# - name: Scale up Prometheus statefulsets

- name: Scale down OpenShift monitoring-related statefulset(s) to reset data
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    api_version: apps/v1
    kind: StatefulSet
    name: "{{ item }}"
    namespace: openshift-monitoring
    resource_definition:
      spec:
        replicas: 0
    wait: true
  loop:
    - "prometheus-k8s"
    - "alertmanager-main"
  when:
    - tools_cluster.platform == "openshift"

- name: Scale down OpenShift user workload monitoring-related statefulset(s) to reset data
  kubernetes.core.k8s:
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    api_version: apps/v1
    kind: StatefulSet
    name: "{{ item }}"
    namespace: openshift-user-workload-monitoring
    resource_definition:
      spec:
        replicas: 0
    wait: true
  loop:
    - "prometheus-user-workload"
    - "alertmanager-user-workload"
    - "thanos-ruler-user-workload"
  when:
    - tools_cluster.platform == "openshift"

# # NOTE: Not needed as installation triggers scale up
# - name: Scale up OpenShift monitoring and user workload monitoring-related statefulsets
