---
- name: Scale down Kubernetes metrics server
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    name: metrics-server
    namespace: "{{ helm_release.namespace }}"
    resource_definition:
      spec:
        replicas: 0
    wait: true

- name: Scale up Kubernetes metrics server
  kubernetes.core.k8s:
    api_version: apps/v1
    kind: Deployment
    kubeconfig: "{{ tools_cluster.kubeconfig }}"
    name: metrics-server
    namespace: "{{ helm_release.namespace }}"
    resource_definition:
      spec:
        replicas: 1
    wait: true
