apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: paa
  name: non-default-sa
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: paa
  name: test-role
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: v1
kind: Pod
metadata:
  namespace: paa
  name: test-untrusted-registry
spec:
  serviceAccountName: non-default-sa
  containers:
    - name: test
      image: untrusted-registry.com/test-image
      securityContext:
        allowPrivilegeEscalation: false
        runAsUser: 1000
