---
- name: Retrieve endpoint url
  ansible.builtin.include_role:
    name: common
    apply:
      tags:
        - install_tools
      vars:
        ingress:
          name: grafana
          namespace: "{{ grafana_namespace_project_name }}"
          path: grafana
        service:
          name: grafana
          namespace: "{{ grafana_namespace_project_name }}"
          port: 80
    tasks_from: fetch_endpoint_url.yaml

- name: Grafana health check
  ansible.builtin.uri:
    url: "{{ endpoint_url }}/healthz"
    method: GET
    status_code: 200
    return_content: true
  register: grafana_health_check
  retries: 5
  delay: 60
  until: grafana_health_check.content == "Ok"
  tags:
    - install_tools
