---
- name: Set up Nginx Ingress
  kubernetes.core.helm:
    name: "{{ ingress_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "{{ ingress_chart_version }}"
    release_namespace: "{{ ingress_namespace_project_name }}"
    release_state: present
    create_namespace: true
    wait: true
    timeout: 20m0s
  ignore_errors: yes