---
- name: Install OpenCost
  kubernetes.core.helm:
    chart_ref: opencost
    chart_repo_url: https://opencost.github.io/opencost-helm-chart
    chart_version: 2.0.1
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    release_name: "{{ helm_release.name }}"
    release_namespace: "{{ helm_release.namespace }}"
    release_state: present
    timeout: 10m0s
    values:
      networkPolicies:
        enabled: true
        prometheus:
          namespace: "{{ prometheus.namespace }}"
      opencost:
        customPricing:
          enabled: true
          createConfigmap: true
          provider: custom
          costModel:
            description: Modified pricing configuration.
            CPU: 10.00
            spotCPU: 7.50
            RAM: 5.00
            spotRAM: 2.50
            GPU: 50.00
            storage: 2.50
            zoneNetworkEgress: 1.00
            regionNetworkEgress: 1.00
            internetNetworkEgress: 1.00
        exporter:
          extraEnv:
            USE_CUSTOM_PROVIDER: true
        metrics:
          serviceMonitor:
            enabled: "{{ prometheus.enabled }}"
        prometheus:
          external:
            enabled: "{{ prometheus.enabled }}"
            url: "{{ prometheus.url }}"
          internal:
            enabled: false
    wait: true
