---
- name: Deploy Kubernetes Topology Mapper
  kubernetes.core.helm:
    name: "{{ topology_mapper_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: tools/kubernetes-topology-mapper/charts/kubernetes-topology-mapper
    dependency_update: true
    release_namespace: "{{ topology_mapper_namespace_project_name }}"
    state: present
    wait: true
    timeout: 10m0s
