---
- name: Add Helm chart repo for Loki
  kubernetes.core.helm_repository:
    name: grafana
    kubeconfig_path: "{{ kubeconfig }}"
    repo_url: "https://grafana.github.io/helm-charts"
  when:
    - enable_loki_endpoint

- name: Update Helm repo
  kubernetes.core.helm:
    name: dummy
    kubeconfig_path: "{{ kubeconfig }}"
    state: absent
    release_namespace: "{{ loki_namespace_project_name }}"
    update_repo_cache: true
  when:
    - enable_loki_endpoint

- name: Deploy Loki
  kubernetes.core.helm:
    name: "{{ loki_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: grafana/loki
    chart_version: "{{ loki_chart_version }}"
    release_namespace: "{{ loki_namespace_project_name }}"
    release_state: present
    create_namespace: true
    wait: true
    timeout: 10m0s
    values:
      backend:
        replicas: 0
      chunksCache:
        enabled: false
      resultsCache:
        enabled: false
      deploymentMode: SingleBinary
      loki:
        auth_enabled: false
        commonConfig:
          replication_factor: 1
        ingester:
          chunk_encoding: snappy
        querier:
          max_concurrent: 2
        schemaConfig:
          configs:
            - from: 2025-01-01
              store: tsdb
              object_store: filesystem
              schema: v13
              index:
                prefix: loki_index_
                period: 24h
        storage:
          type: filesystem
        tracing:
          enabled: true
      lokiCanary:
        enabled: false
      read:
        replicas: 0
      singleBinary:
        replicas: 1
        resources:
          limits:
            cpu: 2
            memory: 2Gi
          requests:
            cpu: 1
            memory: 1Gi
      test:
        enabled: false
      write:
        replicas: 0
  when:
    - enable_loki_endpoint
