---
- name: Install Clickhouse Operator
  kubernetes.core.helm:
    chart_ref: altinity-clickhouse-operator
    chart_repo_url: https://docs.altinity.com/clickhouse-operator/
    chart_version: 0.24.5
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    release_name: "{{ helm_releases.operator.name }}"
    release_namespace: "{{ helm_releases.operator.namespace }}"
    release_state: present
    timeout: 10m0s
    values:
      configs:
        files:
          config.yaml:
            watch:
              namespaces:
                - "{{ helm_releases.instance.namespace }}"
      podAnnotations:
        openshift.io/required-scc: restricted-v2
      serviceMonitor:
        enabled: "{{ observability_tools_enabled.stack.prometheus }}"
    wait: true

- name: Install Clickhouse
  kubernetes.core.helm:
    chart_ref: clickhouse
    chart_repo_url: https://helm.altinity.com
    chart_version: 0.2.2
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    release_name: "{{ helm_releases.instance.name }}"
    release_namespace: "{{ helm_releases.instance.namespace }}"
    release_state: present
    timeout: 10m0s
    values:
      clickhouse:
        defaultUser:
          allowExternalAccess: true
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
        podSecurityContext:
          fsGroup: 101
          runAsGroup: 101
          runAsNonRoot: true
          runAsUser: 101
          seccompProfile:
            type: "RuntimeDefault"
      podAnnotations:
        openshift.io/required-scc: restricted-v2
      operator:
        enabled: false
    wait: true

- name: Wait for Clickhouse install to complete
  kubernetes.core.k8s_info:
    api_version: clickhouse.altinity.com/v1
    kind: ClickHouseInstallation
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    name: "{{ helm_releases.instance.name }}"
    namespace: "{{ helm_releases.instance.namespace }}"
    wait: true
  register: clickhouse_installation_info
  until:
    - clickhouse_installation_info.resources[0].status.status is defined
    - clickhouse_installation_info.resources[0].status.status == 'Completed'
  retries: 10
  delay: 30
