---
- name: Import Observability Stack installation tasks
  ansible.builtin.import_tasks:
    file: install_stack.yaml

- name: Import Kubernetes Topology Monitor installation tasks
  ansible.builtin.import_tasks:
    file: install_kubernetes_topology_monitor.yaml
  tags:
    - install_tools
  vars:
    helm_release: "{{ observability_tools_helm_releases.kubernetes_topology_monitor }}"
  when:
    - observability_tools_enabled.kubernetes.topology_monitor
