---
- name: Import Assertion JSON initialization tasks
  ansible.builtin.import_tasks:
    file: initialize_assertion_json.yaml
  when:
    - (sre_bench_runner | default(false))

- name: Import Prometheus installation tasks
  ansible.builtin.import_tasks:
    file: install_prometheus.yaml
  vars:
    helm_release: "{{ observability_tools_helm_releases.prometheus }}"
  when:
    - observability_tools_enabled.stack.prometheus or observability_tools_enabled.stack.opencost

- name: Import Clickhouse installation tasks
  ansible.builtin.import_tasks:
    file: install_clickhouse.yaml
  vars:
    helm_releases:
      instance: "{{ observability_tools_helm_releases.clickhouse }}"
      operator: "{{ observability_tools_helm_releases.clickhouse_operator }}"
  when:
    - observability_tools_enabled.stack.clickhouse or observability_tools_enabled.stack.opentelemetry

- name: Import OpenSearch installation tasks
  ansible.builtin.import_tasks:
    file: install_opensearch.yaml
  vars:
    helm_release: "{{ observability_tools_helm_releases.opensearch }}"
  when:
    - observability_tools_enabled.stack.opensearch or observability_tools_enabled.stack.jaeger

- name: Import OpenTelemetry installation tasks
  ansible.builtin.import_tasks:
    file: install_opentelemetry.yaml
  vars:
    helm_releases:
      clickhouse: "{{ observability_tools_helm_releases.clickhouse }}"
      collectors: "{{ observability_tools_helm_releases.opentelemetry_collectors }}"
      operator: "{{ observability_tools_helm_releases.opentelemetry_operator }}"
      opensearch: "{{ observability_tools_helm_releases.opensearch }}"
  when:
    - observability_tools_enabled.stack.opentelemetry or observability_tools_enabled.stack.jaeger

- name: Import OpenCost installation tasks
  ansible.builtin.import_tasks:
    file: install_opencost.yaml
  vars:
    helm_release: "{{ observability_tools_helm_releases.opencost }}"
  when:
    - observability_tools_enabled.stack.opencost

- name: Import Ingress installation tasks
  ansible.builtin.import_tasks:
    file: install_ingress.yaml
  vars:
    helm_release: "{{ observability_tools_helm_releases.ingress }}"
  when:
    - observability_tools_enabled.stack.ingress
