---
- name: Install OpenTelemetry Collector for Kubernetes Events
  kubernetes.core.helm:
    chart_ref: opentelemetry-collector
    chart_repo_url: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart_version: 0.122.5
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    release_name: "{{ helm_releases.collectors.names.kubernetes_events }}"
    release_namespace: "{{ helm_releases.collectors.namespace }}"
    release_state: present
    timeout: 10m0s
    values:
      mode: deployment
      replicaCount: 1
      presets:
        kubernetesEvents:
          enabled: true
      image:
        repository: otel/opentelemetry-collector-contrib
        tag: 0.123.0
      podAnnotations:
        openshift.io/required-scc: restricted-v2
      ports:
        jaeger-compact:
          enabled: false
        jaeger-thrift:
          enabled: false
        jaeger-grpc:
          enabled: false
        zipkin:
          enabled: false
        metrics:
          enabled: "{{ observability_tools_enabled.stack.prometheus }}"
      serviceMonitor:
        enabled: "{{ observability_tools_enabled.stack.prometheus }}"
      config:
        exporters:
          clickhouse:
            username: "{{ chart_values.kubernetes_events_collector.clickhouse.user }}"
            password: "{{ chart_values.kubernetes_events_collector.clickhouse.password }}"
            endpoint: "{{ chart_values.kubernetes_events_collector.clickhouse.internal_url }}"
            logs_table_name: otel_k8s_events_logs
        receivers:
          jaeger:
          prometheus:
          zipkin:
        service:
          pipelines:
            logs:
              exporters:
                - debug
                - clickhouse
            metrics:
              receivers:
                - otlp
            traces:
              receivers:
                - otlp
    wait: true
  when:
    - observability_tools_enabled.stack.opentelemetry

- name: Install OpenTelemetry Operator
  kubernetes.core.helm:
    chart_ref: opentelemetry-operator
    chart_repo_url: https://open-telemetry.github.io/opentelemetry-helm-charts
    chart_version: 0.85.0
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    release_name: "{{ helm_releases.operator.name }}"
    release_namespace: "{{ helm_releases.operator.namespace }}"
    release_state: present
    timeout: 10m0s
    values:
      manager:
        collectorImage:
          repository: otel/opentelemetry-collector-k8s
        podAnnotations:
          openshift.io/required-scc: restricted-v2
        serviceMonitor:
          enabled: "{{ observability_tools_enabled.stack.prometheus }}"
      admissionWebhooks:
        certManager:
          enabled: false
        autoGenerateCert:
          enabled: true
      securityContext:
        fsGroup:
    wait: true
  when:
    - observability_tools_enabled.stack.jaeger

- name: Install Jaeger
  kubernetes.core.k8s:
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: opentelemetry.io/v1beta1
      kind: OpenTelemetryCollector
      metadata:
        name: jaeger
        namespace: "{{ helm_releases.collectors.namespace }}"
      spec:
        image: jaegertracing/jaeger:2.6.0
        observability:
          metrics:
            enableMetrics: true
        podAnnotations:
          openshift.io/required-scc: restricted-v2
        ports:
          - name: jaeger
            port: 16686
        config: "{{ lookup('ansible.builtin.template', 'templates/otel-jaeger-config.j2') | from_yaml }}"
  when:
    - observability_tools_enabled.stack.jaeger

- name: Wait for Jaeger Collector pods to be ready
  kubernetes.core.k8s_info:
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    kind: Pod
    namespace: "{{ helm_releases.collectors.namespace }}"
    label_selectors:
      - "app.kubernetes.io/name=jaeger-collector"
      - "app.kubernetes.io/instance=opentelemetry-collectors.jaeger"
      - "app.kubernetes.io/managed-by=opentelemetry-operator"
    wait: true
    wait_sleep: 30
    wait_timeout: 600
    wait_condition:
      type: Ready
      status: "True"
  when:
    - observability_tools_enabled.stack.jaeger
