---
- name: Create the release namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ helm_release.namespace }}"
        labels:
          it-bench/monitoring: "true"
    state: present
  when:
    - observability_tools_cluster.platform == "kubernetes"

- name: Install Prometheus Operator and Prometheus
  kubernetes.core.helm:
    chart_ref: kube-prometheus-stack
    chart_repo_url: https://prometheus-community.github.io/helm-charts
    chart_version: 72.3.0
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    release_name: "{{ helm_release.name }}"
    release_namespace: "{{ helm_release.namespace }}"
    release_state: present
    timeout: 10m0s
    values:
      grafana:
        enabled: false
      prometheus:
        prometheusSpec:
          ruleNamespaceSelector:
            matchLabels:
              it-bench/monitoring: "true"
          ruleSelectorNilUsesHelmValues: false
          serviceMonitorNamespaceSelector:
            matchLabels:
              it-bench/monitoring: "true"
          serviceMonitorSelectorNilUsesHelmValues: false
    wait: true
  when:
    - observability_tools_cluster.platform == "kubernetes"

- name: Enable OpenShift user workload monitoring
  kubernetes.core.k8s:
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    state: present
    src: files/ocp/user-workload-monitoring-config.yaml
  when:
    - observability_tools_cluster.platform == "openshift"

- name: Wait for Prometheus workload pods to start
  kubernetes.core.k8s_info:
    kind: Pod
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    label_selectors:
      - app.kubernetes.io/component = prometheus
      - app.kubernetes.io/instance = user-workload
    namespace: openshift-user-workload-monitoring
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_timeout: 300
  when:
    - observability_tools_cluster.platform == "openshift"
