---
- name: Create the release namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ helm_release.namespace }}"
        labels:
          it-bench/monitoring: "true"
    state: present
  when:
    - observability_tools_cluster.platform == "kubernetes"

- name: Install Nginx Ingress
  kubernetes.core.helm:
    chart_ref: ingress-nginx
    chart_repo_url: https://kubernetes.github.io/ingress-nginx
    chart_version: 4.12.1
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    release_name: "{{ helm_release.name }}"
    release_namespace: "{{ helm_release.namespace }}"
    release_state: present
    timeout: 20m0s
    values:
      controller:
        addHeaders:
          "X-Content-Type-Options": nosniff
          "X-Frame-Options": DENY
          "X-XSS-Protection": "0"
          "Strict-Transport-Security": max-age=31536000; includeSubDomains; preload
          "Content-Security-Policy": "img-src 'self' data:; connect-src 'self'; font-src 'self'; object-src 'none'; form-action 'none'; frame-ancestors 'none'"
          "Cross-Origin-Resource-Policy": same-origin
          "Referrer-Policy": strict-origin-when-cross-origin
        config:
          server-tokens: "false"
        service:
          type: "{{ 'NodePort' if (observability_tools_cluster.provider == 'kind') else 'LoadBalancer' }}"
        metrics:
          enabled: "{{ observability_tools_enabled.stack.prometheus }}"
          serviceMonitor:
            enabled: "{{ observability_tools_enabled.stack.prometheus }}"
    wait: true
  when:
    - observability_tools_cluster.platform == "kubernetes"

- name: Create Ingress objects for Observability Stack
  kubernetes.core.k8s:
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    state: present
    template: templates/stack-ingress.j2
  when:
    - observability_tools_cluster.platform == "kubernetes"
    - (lookup('ansible.builtin.template', 'templates/stack-ingress.j2') | trim) != ""

- name: Create Route objects for Observability Stack
  kubernetes.core.k8s:
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    resource_definition:
      apiVersion: route.openshift.io/v1
      kind: Route
      metadata:
        name: "{{ item.name }}"
        namespace: "{{ item.namespace }}"
      spec:
        httpHeaders:
          actions:
            response: "{{ lookup('ansible.builtin.file', 'files/ocp/route-response-actions.yaml') | from_yaml }}"
        port:
          targetPort: "{{ item.port }}"
        to:
          kind: Service
          name: "{{ item.service }}"
    state: present
  loop:
    - enabled: "{{ observability_tools_enabled.stack.clickhouse }}"
      name: "{{ observability_tools_helm_releases.clickhouse.name }}"
      namespace: "{{ observability_tools_helm_releases.clickhouse.namespace }}"
      port: 8123
      service: "{{ observability_tools_helm_releases.clickhouse.name }}-clickhouse"
    - enabled: "{{ observability_tools_enabled.stack.jaeger }}"
      name: jaeger-collector
      namespace: "{{ observability_tools_helm_releases.opentelemetry_collectors.namespace }}"
      port: 16686
      service: jaeger-collector
    - enabled: "{{ observability_tools_enabled.stack.opencost }}"
      name: "{{ observability_tools_helm_releases.opencost.name }}"
      namespace: "{{ observability_tools_helm_releases.opencost.namespace }}"
      port: 9090
      service: "{{ observability_tools_helm_releases.opencost.name }}"
  when:
    - observability_tools_cluster.platform == "openshift"
    - item.enabled
