---
- name: Deploy OpenTelemetry Collector (Kubernetes)
  kubernetes.core.helm:
    name: "{{ opentelemetry_collector_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: open-telemetry/opentelemetry-collector
    chart_version: "{{ opentelemetry_collector_chart_version }}"
    release_namespace: "{{ opentelemetry_collector_namespace_project_name }}"
    release_state: present
    wait: true
    timeout: 10m0s
    create_namespace: true
    values:
      mode: deployment
      replicaCount: 1
      presets:
        kubernetesEvents:
          enabled: true
      image:
        repository: "otel/opentelemetry-collector-k8s"
      config:
        exporters:
          otlphttp/logs:
            endpoint: http://{{ loki_installation_name }}-gateway.{{ loki_namespace_project_name }}.svc.cluster.local/otlp
            tls:
              insecure: true
        receivers:
          jaeger: null
          prometheus: null
          zipkin: null
        service:
          pipelines:
            logs:
              exporters: 
                - debug
                - otlphttp/logs
            metrics:
              receivers:
                - otlp
            traces:
              receivers:
                - otlp
