---
- name: Set Context Security Policies
  ansible.builtin.set_fact:
    security_policies:
      - "img-src 'self' data:"
      - form-action 'none'
      - frame-ancestors 'none'

- name: Set up Nginx Ingress
  kubernetes.core.helm:
    name: "{{ ingress_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "{{ ingress_chart_version }}"
    release_namespace: "{{ ingress_namespace_project_name }}"
    release_state: present
    create_namespace: true
    wait: true
    timeout: 20m0s
    values:
      controller:
        addHeaders:
          "Content-Security-Policy": "{{ security_policies | join('; ') }}"
          "X-Content-Type-Options": nosniff
