---
- name: Deploy OpenSearch
  kubernetes.core.helm:
    name: "{{ opensearch_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: opensearch/opensearch
    chart_version: "{{ opensearch_chart_version }}"
    release_namespace: "{{ opensearch_namespace_project_name }}"
    release_state: present
    create_namespace: true
    wait: true
    values:
      replicas: 1
      config:
        opensearch.yml: |
          cluster.name: opensearch-cluster
          # Bind to all interfaces because we don't know what IP address will be assigned
          network.host: 0.0.0.0
          plugins.security.disabled: true
      extraEnvs:
      - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        value: "Opensearch@admin@password@1234"

- name: Deploy Ingress for OpenTelemetry Collector (Jaeger)
  kubernetes.core.k8s:
    state: present
    kubeconfig: "{{ kubeconfig }}"
    resource_definition:
      apiVersion: networking.k8s.io/v1
      kind: Ingress
      metadata:
        name: opensearch
        namespace: "{{ opensearch_namespace_project_name }}"
        annotations:
          nginx.ingress.kubernetes.io/rewrite-target: /$2
      spec:
        ingressClassName: nginx
        rules:
          - http:
              paths:
                - pathType: ImplementationSpecific
                  path: /opensearch(/|$)(.*)
                  backend:
                    service:
                      name: "{{ opensearch_installation_name }}-cluster-master"
                      port:
                        number: 9200
