---
- name: Create namespace(s) for observability components
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: v1
      kind: Namespace
      metadata:
        name: "{{ ingress_namespace_project_name }}"

- name: Create ConfigMap with security headers
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: security-headers
        namespace: "{{ ingress_namespace_project_name }}"
      data:
        X-Content-Type-Options: "nosniff"
        X-Frame-Options: "DENY"
        X-XSS-Protection: "0"
        Strict-Transport-Security: "max-age=31536000; includeSubDomains; preload"
        Content-Security-Policy: "img-src 'self' data:; connect-src 'self'; font-src 'self'; object-src 'none'; form-action 'none'; frame-ancestors 'none'"
        Cross-Origin-Resource-Policy: "same-origin"
        Referrer-Policy: "strict-origin-when-cross-origin"

- name: Set up Nginx Ingress
  kubernetes.core.helm:
    name: "{{ ingress_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: ingress-nginx/ingress-nginx
    chart_version: "{{ ingress_chart_version }}"
    release_namespace: "{{ ingress_namespace_project_name }}"
    release_state: present
    wait: true
    timeout: 20m0s
    values:
      controller:
        config:
          add-headers: "{{ ingress_namespace_project_name }}/security-headers"
          server-tokens: "false"
  ignore_errors: yes
