---
- name: Install Nginx Ingress
  kubernetes.core.helm:
    chart_ref: ingress-nginx
    chart_repo_url: https://kubernetes.github.io/ingress-nginx
    chart_version: 4.12.1
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    release_name: "{{ helm_release.name }}"
    release_namespace: "{{ helm_release.namespace }}"
    release_state: present
    timeout: 20m0s
    values:
      controller:
        addHeaders:
          "X-Content-Type-Options": nosniff
          "X-Frame-Options": DENY
          "X-XSS-Protection": "0"
          "Strict-Transport-Security": max-age=31536000; includeSubDomains; preload
          "Content-Security-Policy": "{{ observability_tools_content_security_policies | join('; ') }}"
          "Cross-Origin-Resource-Policy": same-origin
          "Referrer-Policy": strict-origin-when-cross-origin
        config:
          server-tokens: "false"
        service:
          type: "{{ 'NodePort' if (cluster_type is defined and ((cluster_type == 'kind_local') or (cluster_type == 'openshift_crc_local'))) else 'LoadBalancer' }}"
        metrics:
          enabled: "{{ observability_tools_enabled.stack.prometheus }}"
          serviceMonitor:
            enabled: "{{ observability_tools_enabled.stack.prometheus }}"
    wait: true

- name: Create Ingress objects for Observability Stack
  kubernetes.core.k8s:
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    state: present
    template: templates/stack-ingress.j2
