---
- name: Create custom Security Context Constraint (SCC) for OpenSearch
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: security.openshift.io/v1
      kind: SecurityContextConstraints
      metadata:
        name: opensearch-scc
      allowPrivilegedContainer: true
      readOnlyRootFilesystem: false
      defaultAddCapabilities: []
      requiredDropCapabilities:
        - ALL
      runAsUser:
        type: RunAsAny
      seLinuxContext:
        type: RunAsAny
      fsGroup:
        type: RunAsAny
      supplementalGroups:
        type: RunAsAny
      seccompProfiles:
        - 'runtime/default'
  when:
    - (is_openshift | default(false))

- name: Apply SCC to all service accounts in the OpenSearch namespace
  ansible.builtin.command:
    cmd: >
      oc adm policy add-scc-to-group opensearch-scc system:serviceaccounts:{{ item }}
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  loop:
    - "{{ opensearch_namespace_project_name }}"
  when:
    - (is_openshift | default(false))

- name: Deploy OpenSearch
  kubernetes.core.helm:
    name: "{{ opensearch_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: opensearch/opensearch
    chart_version: "{{ opensearch_chart_version }}"
    release_namespace: "{{ opensearch_namespace_project_name }}"
    release_state: present
    create_namespace: true
    wait: true
    timeout: 10m
    values:
      replicas: 1
      config:
        opensearch.yml: |
          cluster.name: opensearch-cluster
          # Bind to all interfaces because we don't know what IP address will be assigned
          network.host: 0.0.0.0
          plugins.security.disabled: true
      extraEnvs:
      - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
        value: "Opensearch@admin@password@1234"
      persistence:
        enabled: true
        enableInitChown: false
