---
- name: Deploy Jaeger
  kubernetes.core.helm:
    name: "{{ jaeger_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    chart_ref: jaegertracing/jaeger
    chart_version: "{{ jaeger_chart_version }}"
    release_namespace: "{{ jaeger_namespace_project_name }}"
    release_state: present
    create_namespace: true
    wait: true
    timeout: 10m0s
    values:
      collector:
        service:
          otlp:
            http:
              name: "otlp-http"
              port: 4318
            grpc:
              name: "otlp-grpc"
              port: 4317
          zipkin:
            port: 9411
      prometheus:
        query:
          support-spanmetrics-connector: true
        server-url: "http://{{ prometheus_service_name }}.{{ prometheus_namespace_project_name }}:9090"
      provisionDataStore:
        cassandra: false
      query:
        enabled: "{{ true if (enable_jaeger_query_endpoint | lower | bool) else false }}"
      storage:
        elasticsearch:
          host: "{{ es_installation_name }}-elasticsearch.{{ es_namespace_project_name }}"
          port: 9200
        type: elasticsearch