---
- name: Install OpenSearch
  kubernetes.core.helm:
    chart_ref: opensearch
    chart_repo_url: https://opensearch-project.github.io/helm-charts
    chart_version: 2.32.0
    kubeconfig: "{{ kubeconfig }}"
    release_name: "{{ helm_release.name }}"
    release_namespace: "{{ helm_release.namespace }}"
    release_state: present
    timeout: 10m
    values:
      replicas: 1
      config:
        opensearch.yml: |
          cluster.name: opensearch-cluster
          # Bind to all interfaces because we don't know what IP address will be assigned
          network.host: 0.0.0.0
          plugins.security.disabled: true
      extraEnvs:
        - name: OPENSEARCH_INITIAL_ADMIN_PASSWORD
          value: "Opensearch@admin@password@1234"
      persistence:
        enabled: true
        enableInitChown: false
    wait: true
