---
- name: Initialize Helm charts for observability tools
  ansible.builtin.import_tasks:
    file: set_up_helm_charts.yaml

- name: Install Ingress NGINX Controller
  ansible.builtin.import_tasks:
    file: install_ingress.yaml

- name: Install Jaeger
  ansible.builtin.import_tasks:
    file: install_jaeger.yaml
  when:
    - tools | intersect(['jaeger']) | length == 1

- name: Install Grafana Loki
  ansible.builtin.import_tasks:
    file: install_loki.yaml
  when:
    - tools | intersect(['loki', 'kubernetes-event-exporter']) | length > 0

- name: Install OpenSearch
  ansible.builtin.import_tasks:
    file: install_opensearch.yaml
  when:
    - tools | intersect(['opensearch']) | length == 1

- name: Install Prometheus
  ansible.builtin.import_tasks:
    file: install_prometheus.yaml

- name: Wait for Grafana datasource services
  kubernetes.core.helm_info:
    kubeconfig_path: "{{ kubeconfig }}"
    release_name: "{{ item.name }}"
    release_namespace: "{{ item.namespace }}"
  loop:
    - name: "{{ jaeger_namespace_project_name }}"
      namespace: "{{ jaeger_installation_name }}"
    - name: "{{ loki_namespace_project_name }}"
      namespace: "{{ loki_installation_name }}"
    - name: "{{ opensearch_namespace_project_name }}"
      namespace: "{{ opensearch_installation_name }}"
    - name: "{{ prometheus_installation_name }}"
      namespace: "{{ prometheus_namespace_project_name }}"
  register: helm_info
  until: helm_info.status.status == 'deployed'
  retries: 10
  delay: 60

- name: Install Kubernetes Event Exporter (OpenTelemetry)
  ansible.builtin.import_tasks:
    file: install_opentelemetry_collector.yaml
  when:
    - tools | intersect(['kubernetes-event-exporter']) | length == 1

- name: Install Grafana
  ansible.builtin.import_tasks:
    file: install_grafana.yaml

- name: Install Opencost
  ansible.builtin.import_tasks:
    file: install_opencost.yaml
  when:
    - tools | intersect(['opencost']) | length == 1
