---
- ansible.builtin.import_tasks:
    file: initialize_assertion_json.yaml
  tags:
    - install_tools
  when:
    - sre_bench_runner

- ansible.builtin.import_tasks:
    file: set_up_helm_charts.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_ingress.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_clickhouse.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_loki.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_opensearch.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_jaeger.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_prometheus.yaml
  tags:
    - install_tools

- name: List of common (SRE+FinOps) Helm installations
  ansible.builtin.set_fact:
    common_helm_installations:
      - name: "{{ loki_namespace_project_name }}"
        namespace: "{{ loki_installation_name }}"
      - name: "{{ opensearch_namespace_project_name }}"
        namespace: "{{ opensearch_installation_name }}"
      - name: "{{ jaeger_namespace_project_name }}"
        namespace: "{{ jaeger_installation_name }}"
      - name: "{{ prometheus_namespace_project_name }}"
        namespace: "{{ prometheus_installation_name }}"

- name: Wait for common (SRE + FinOps) installations to complete
  ansible.builtin.command: "helm status {{ item.name }} -n {{ item.namespace }}"
  register: helm_status
  until: "helm_status.rc == 0 and helm_status.stdout.find('STATUS: deployed') != -1"
  retries: 10
  delay: 60
  loop: "{{ common_helm_installations }}"

- ansible.builtin.import_tasks:
    file: install_opentelemetry_collector.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_grafana.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_metrics_server.yaml
  tags:
    - install_tools
  when:
    - domain == "finops"

- ansible.builtin.import_tasks:
    file: install_opencost.yaml
  tags:
    - install_tools
  when:
    - domain == "finops"

- name: List of common FinOps Helm installations
  ansible.builtin.set_fact:
    finops_related_helm_installations:
      - name: "{{ opencost_installation_name }}"
        namespace:  "{{ opencost_namespace_project_name }}"
      - name: "{{ metrics_server_installation_name }}"
        namespace: "{{ metrics_server_namespace_project_name }}"

- name: Wait for common FinOps installations to complete
  ansible.builtin.command: "helm status {{ item.name }} -n {{ item.namespace }}"
  register: helm_status
  until: "helm_status.rc == 0 and helm_status.stdout.find('STATUS: deployed') != -1"
  retries: 10
  delay: 60
  loop: "{{ finops_related_helm_installations }}"
  when:
    - domain == "finops"

- ansible.builtin.import_tasks:
    file: check_grafana_status.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: uninstall_observability_stack.yaml
  tags:
    - uninstall_tools

- ansible.builtin.import_tasks:
    file: finalize_assertion_json.yaml
  tags:
    - uninstall_tools
  when:
    - sre_bench_runner
