---
- ansible.builtin.import_tasks:
    file: initialize_assertion_json.yaml
  tags:
    - install_tools
  when:
    - (sre_bench_runner | default(false))

- ansible.builtin.import_tasks:
    file: set_up_helm_charts.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: set_up_namespaces.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: set_up_service_account_scc_for_openshift.yaml
  tags:
    - install_tools
  when:
    - cluster_type is defined
    - cluster_type == "openshift" or cluster_type == "openshift_crc_local"

- ansible.builtin.import_tasks:
    file: install_ingress.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_clickhouse.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_opensearch.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_prometheus.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_opentelemetry.yaml
  tags:
    - install_tools

- ansible.builtin.import_tasks:
    file: install_metrics_server.yaml
  tags:
    - install_tools
  when:
    - domain == "finops"
    - cluster_type is undefined
    - cluster_type is defined and (cluster_type == "kops" or cluster_type == "kind_local")

- ansible.builtin.import_tasks:
    file: install_opencost.yaml
  tags:
    - install_tools
  when:
    - domain == "finops"

- ansible.builtin.import_tasks:
    file: uninstall_observability_stack.yaml
  tags:
    - uninstall_tools

- ansible.builtin.import_tasks:
    file: finalize_assertion_json.yaml
  tags:
    - uninstall_tools
  when:
    - (sre_bench_runner | default(false))
