---
- name: Create custom Security Context Constraint (SCC) for Clickhouse, OpenTelemetry operator plus collector and OpenCost
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: security.openshift.io/v1
      kind: SecurityContextConstraints
      metadata:
        name: clickhouse-otel-opencost-scc
      allowPrivilegedContainer: false
      readOnlyRootFilesystem: false
      defaultAddCapabilities: []
      requiredDropCapabilities:
        - ALL
      runAsUser:
        type: MustRunAsNonRoot
      seLinuxContext:
        type: RunAsAny
      fsGroup:
        type: RunAsAny
      supplementalGroups:
        type: RunAsAny
      seccompProfiles:
        - 'runtime/default'

- name: Apply SCC to all service accounts in a Clickhouse and Opentelemetry operator namespaces
  ansible.builtin.command:
    cmd: >
      oc adm policy add-scc-to-group clickhouse-otel-opencost-scc system:serviceaccounts:{{ item }}
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  loop:
    - "{{ clickhouse_namespace_project_name }}"
    - "{{ opencost_namespace_project_name }}"
    - "{{ opentelemetry_operator_namespace_project_name }}"

- name: Create Security Context Constraint (SCC) for Prometheus and Ingress-Nginx
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: security.openshift.io/v1
      kind: SecurityContextConstraints
      metadata:
        name: prometheus-ingress-nginx-scc
      allowPrivilegedContainer: false
      readOnlyRootFilesystem: false
      allowedCapabilities:
        - NET_BIND_SERVICE
      defaultAddCapabilities: []
      requiredDropCapabilities:
        - ALL
      runAsUser:
        type: MustRunAsNonRoot
      seLinuxContext:
        type: RunAsAny
      fsGroup:
        type: RunAsAny
      supplementalGroups:
        type: RunAsAny
      allowHostDirVolumePlugin: true
      allowHostNetwork: true
      allowHostPorts: true
      allowHostPID: true
      seccompProfiles:
        - 'runtime/default'

- name: Apply SCC to all service accounts in the Prometheus and Ingress-Nginx namespace
  ansible.builtin.command:
    cmd: >
      oc adm policy add-scc-to-group prometheus-ingress-nginx-scc system:serviceaccounts:{{ item }}
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  loop:
    - "{{ prometheus_namespace_project_name }}"
    - "{{ ingress_namespace_project_name }}"
    - "{{ metrics_server_namespace_project_name }}"

- name: Create custom Security Context Constraint (SCC) for OpenSearch
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: security.openshift.io/v1
      kind: SecurityContextConstraints
      metadata:
        name: opensearch-scc
      allowPrivilegedContainer: true
      readOnlyRootFilesystem: false
      defaultAddCapabilities: []
      requiredDropCapabilities:
        - ALL
      runAsUser:
        type: RunAsAny
      seLinuxContext:
        type: RunAsAny
      fsGroup:
        type: RunAsAny
      supplementalGroups:
        type: RunAsAny
      seccompProfiles:
        - 'runtime/default'

- name: Apply SCC to all service accounts in the OpenSearch namespace
  ansible.builtin.command:
    cmd: >
      oc adm policy add-scc-to-group opensearch-scc system:serviceaccounts:{{ item }}
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  loop:
    - "{{ opensearch_namespace_project_name }}"
