---
- name: Create custom Security Context Constraint (SCC) for Clickhouse, OpenTelemetry operator plus collector, OpenSearch and OpenCost
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: security.openshift.io/v1
      kind: SecurityContextConstraints
      metadata:
        name: clickhouse-otel-opensearch-opencost-scc
      allowPrivilegedContainer: false
      runAsUser:
        type: RunAsAny
      seLinuxContext:
        type: RunAsAny
      fsGroup:
        type: RunAsAny
      supplementalGroups:
        type: RunAsAny
      seccompProfiles:
        - '*'

- name: Apply SCC to all service accounts in a Clickhouse and Opentelemetry operator namespaces
  ansible.builtin.command:
    cmd: >
      oc adm policy add-scc-to-group clickhouse-otel-opensearch-opencost-scc system:serviceaccounts:{{ item }}
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  loop:
    - "{{ clickhouse_namespace_project_name }}"
    - "{{ opensearch_namespace_project_name }}"
    - "{{ opencost_namespace_project_name }}"
    - "{{ opentelemetry_operator_namespace_project_name }}"

- name: Create Security Context Constraint (SCC) for Prometheus and Ingress-Nginx
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    resource_definition:
      apiVersion: security.openshift.io/v1
      kind: SecurityContextConstraints
      metadata:
        name: prometheus-ingress-nginx-scc
      allowPrivilegedContainer: false
      allowedCapabilities:
        - NET_BIND_SERVICE
      runAsUser:
        type: RunAsAny
      seLinuxContext:
        type: RunAsAny
      fsGroup:
        type: RunAsAny
      supplementalGroups:
        type: RunAsAny
      allowHostDirVolumePlugin: true
      allowHostNetwork: true
      allowHostPorts: true
      allowHostPID: true
      seccompProfiles:
        - '*'

- name: Apply SCC to all service accounts in the Prometheus and Ingress-Nginx namespace
  ansible.builtin.command:
    cmd: >
      oc adm policy add-scc-to-group prometheus-ingress-nginx-scc system:serviceaccounts:{{ item }}
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  loop:
    - "{{ prometheus_namespace_project_name }}"
    - "{{ ingress_namespace_project_name }}"
    - "{{ metrics_server_namespace_project_name }}"
