---
- name: Create custom Security Context Constraints
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    src: files/security-context-constraints.yaml

- name: Apply SCC to all service accounts in a Clickhouse and Opentelemetry operator namespaces
  ansible.builtin.command:
    argv:
      - oc
      - adm
      - policy
      - add-scc-to-group
      - "{{ item.scc }}"
      - system:serviceaccounts:{{ item.namespace }}
  environment:
    KUBECONFIG: "{{ kubeconfig }}"
  loop:
    - scc: it-bench-restrictive-scc
      namespace: "{{ clickhouse_namespace_project_name }}"
    - scc: it-bench-restrictive-scc
      namespace: "{{ opencost_namespace_project_name }}"
    - scc: it-bench-restrictive-scc
      namespace: "{{ opentelemetry_operator_namespace_project_name }}"
    - scc: it-bench-allow-host-capabilities-scc
      namespace: "{{ prometheus_namespace_project_name }}"
    - scc: it-bench-allow-host-capabilities-scc
      namespace: "{{ ingress_namespace_project_name }}"
    - scc: it-bench-allow-host-capabilities-scc
      namespace: "{{ metrics_server_namespace_project_name }}"
    - scc: it-bench-allow-priveleged-container-scc
      namespace: "{{ opensearch_namespace_project_name }}"
