---
- name: Remove operator managed resources
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    delete_all: true
    api_version: "{{ item.api_version }}"
    namespace: "{{ item.namespace }}"
    kind: "{{ item.kind }}"
    state: absent
    wait: true
  loop:
    - api_version: clickhouse-keeper.altinity.com/v1
      kind: ClickHouseKeeperInstallation
      namespace: "{{ clickhouse_namespace_project_name }}"
    - api_version: clickhouse.altinity.com/v1
      kind: ClickHouseInstallation
      namespace: "{{ clickhouse_namespace_project_name }}"
    - api_version: clickhouse.altinity.com/v1
      kind: ClickHouseInstallationTemplate
      namespace: "{{ clickhouse_namespace_project_name }}"
    - api_version: clickhouse.altinity.com/v1
      kind: ClickHouseOperatorConfiguration
      namespace: "{{ clickhouse_namespace_project_name }}"
    - api_version: opentelemetry.io/v1beta1
      kind: OpenTelemetryCollector
      namespace: "{{ opentelemetry_operator_collectors_namespace }}"
  register: resource_deletion
  failed_when:
    - resource_deletion.failed
    - not ('Failed to find exact match' in resource_deletion.msg)

- name: Remove the secret(s) associated with Clickhouse (holding up Helm uninstall for Clickhouse)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: v1
    kind: Secret
    name: "sh.helm.release.v1.clickhouse.v1"
    namespace: "{{ clickhouse_namespace_project_name }}"
    state: absent
    wait: true

- name: Remove the Custom Resource Definitions (CRDs)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    delete_all: true
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: "{{ item }}"
    state: absent
    wait: true
  loop:
    - clickhouseinstallations.clickhouse.altinity.com
    - clickhouseinstallationtemplates.clickhouse.altinity.com
    - clickhousekeeperinstallations.clickhouse-keeper.altinity.com
    - clickhouseoperatorconfigurations.clickhouse.altinity.com
    - opentelemetrycollectors.opentelemetry.io
    - opampbridges.opentelemetry.io
    - instrumentations.opentelemetry.io
    - targetallocators.opentelemetry.io
  register: crd_deletion
  failed_when:
    - crd_deletion.failed
    - not ('Failed to find exact match' in crd_deletion.msg)

- name: Remove RBAC objects
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: absent
    template: templates/rbac.j2
    wait: true

# - name: Remove OCP User Workload Monitoring
#   kubernetes.core.k8s:
#     kubeconfig: "{{ kubeconfig }}"
#     state: absent
#     src: files/openshift-user-workload-monitoring.yaml
#     wait: true
#   when:
#     - cluster_type is defined
#     - cluster_type == "openshift" or cluster_type == "openshift_crc_local"

- name: Remove custom Security Context Constraints (SCC) on OpenShift
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: absent
    src: files/security-context-constraints.yaml
    wait: true
  when:
    - cluster_type is defined
    - cluster_type == "openshift" or cluster_type == "openshift_crc_local"

- name: Uninstall OpenTelemetry Operator
  kubernetes.core.helm:
    name: "{{ opentelemetry_operator_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ opentelemetry_operator_namespace_project_name }}"
    state: absent
    wait: true
    timeout: 10m

- name: Uninstall OpenSearch
  kubernetes.core.helm:
    name: "{{ opensearch_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ opensearch_namespace_project_name }}"
    state: absent
    wait: true
    timeout: 10m

- name: Uninstall Clickhouse
  kubernetes.core.helm:
    name: "{{ clickhouse_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ clickhouse_namespace_project_name }}"
    state: absent
    wait: true
    timeout: 10m

- name: Uninstall the Prometheus stack
  kubernetes.core.helm:
    name: "{{ prometheus_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ prometheus_namespace_project_name }}"
    state: absent
    wait: true
    timeout: 10m

- name: Uninstall the Kubernetes Metrics Server
  kubernetes.core.helm:
    name: "{{ metrics_server_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ metrics_server_namespace_project_name }}"
    state: absent
    wait: true
    timeout: 10m

- name: Uninstall the Kubernetes topology mapper
  kubernetes.core.helm:
    name: "{{ topology_mapper_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ topology_mapper_namespace_project_name }}"
    state: absent
    wait: true
    timeout: 10m

- name: Uninstall OpenCost
  kubernetes.core.helm:
    name: "{{ opencost_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ opencost_namespace_project_name }}"
    state: absent
    wait: true
    timeout: 10m

- name: Uninstall Ingress
  kubernetes.core.helm:
    name: "{{ ingress_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ ingress_namespace_project_name }}"
    state: absent
    wait: true
    timeout: 10m

- name: Remove all namespaces
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: absent
    template: templates/namespaces.j2
    wait: true
