---
- name: Uninstall OpenTelemetry Collector (Kubernetes)
  kubernetes.core.helm:
    name: "{{ opentelemetry_collector_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ opentelemetry_collector_namespace_project_name }}"
    state: absent
    wait: true

- name: Remove the namespace associated with OpenTelemetry Collector (Kubernetes)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ opentelemetry_collector_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
