---
- name: Uninstall Ingress NGINX Controller
  ansible.builtin.import_tasks:
    file: uninstall_ingress.yaml

- name: Uninstall Grafana Loki
  ansible.builtin.import_tasks:
    file: uninstall_loki.yaml
  when:
    - tools | intersect(['loki']) | length > 0

- name: Uninstall OpenSearch
  ansible.builtin.import_tasks:
    file: uninstall_opensearch.yaml
  when:
    - tools | intersect(['opensearch']) | length == 1

- name: Uninstall Jaeger
  ansible.builtin.import_tasks:
    file: uninstall_jaeger.yaml
  when:
    - tools | intersect(['jaeger']) | length == 1

- name: Uninstall Prometheus
  ansible.builtin.import_tasks:
    file: uninstall_prometheus.yaml

- name: Uninstall Kubernetes Event Exporter (OpenTelemetry)
  ansible.builtin.import_tasks:
    file: uninstall_opentelemetry_collector.yaml
  when:
    - tools | intersect(['kubernetes-event-exporter']) | length == 1

- name: Uninstall Grafana
  ansible.builtin.import_tasks:
    file: uninstall_grafana.yaml

- name: Uninstall Kubernetes Metrics Server
  ansible.builtin.import_tasks:
    file: uninstall_metrics_server.yaml
  when:
    - tools | intersect(['kubernetes-metrics-server']) | length == 1

- name: Uninstall Opencost
  ansible.builtin.import_tasks:
    file: uninstall_opencost.yaml
  when:
    - tools | intersect(['opencost']) | length == 1
