---
- name: Import Kubernetes Topology Monitor uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_kubernetes_topology_monitor.yaml
  vars:
    helm_release: "{{ observability_tools_helm_releases.kubernetes_topology_monitor }}"
  when:
    - observability_tools_enabled.kubernetes.topology_monitor

- name: Import Observability Stack uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_stack.yaml
