---
- name: Uninstall the Kubernetes Topology Monitor
  kubernetes.core.helm:
    kubeconfig: "{{ kubeconfig }}"
    release_state: absent
    release_name: "{{ helm_release.name }}"
    release_namespace: "{{ helm_release.namespace }}"
    wait: true
