---
- name: Create list of tools to uninstall
  ansible.builtin.set_fact:
    observability_releases:
      - name: "{{ clickhouse_installation_name }}"
        namespace: "{{ clickhouse_namespace_project_name }}"
      - name: "{{ ingress_installation_name }}"
        namespace: "{{ ingress_namespace_project_name }}"
      - name: "{{ prometheus_installation_name }}"
        namespace: "{{ prometheus_namespace_project_name }}"
      - name: "{{ grafana_installation_name }}"
        namespace: "{{ grafana_namespace_project_name }}"
      - name: "{{ opentelemetry_operator_installation_name }}"
        namespace: "{{ opentelemetry_operator_namespace_project_name }}"
      - name: "{{ opencost_installation_name }}"
        namespace: "{{ opencost_namespace_project_name }}"
      - name: "{{ opensearch_installation_name }}"
        namespace: "{{ opensearch_namespace_project_name }}"

- name: Remove operator managed resources
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    delete_all: true
    api_version: "{{ item.api_version }}"
    namespace: "{{ item.namespace }}"
    kind: "{{ item.kind }}"
    state: absent
    wait: true
  loop:
    - api_version: clickhouse-keeper.altinity.com/v1
      kind: ClickHouseKeeperInstallation
      namespace: "{{ clickhouse_namespace_project_name }}"
    - api_version: clickhouse.altinity.com/v1
      kind: ClickHouseInstallation
      namespace: "{{ clickhouse_namespace_project_name }}"
    - api_version: clickhouse.altinity.com/v1
      kind: ClickHouseInstallationTemplate
      namespace: "{{ clickhouse_namespace_project_name }}"
    - api_version: clickhouse.altinity.com/v1
      kind: ClickHouseOperatorConfiguration
      namespace: "{{ clickhouse_namespace_project_name }}"
    - api_version: opentelemetry.io/v1beta1
      kind: OpenTelemetryCollector
      namespace: "{{ opentelemetry_operator_collectors_namespace }}"

- name: Remove the Custom Resource Definitions (CRDs)
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    delete_all: true
    api_version: apiextensions.k8s.io/v1
    kind: CustomResourceDefinition
    name: "{{ item }}"
    state: absent
    wait: true
  loop:
    - clickhouseinstallations.clickhouse.altinity.com
    - clickhouseinstallationtemplates.clickhouse.altinity.com
    - clickhousekeeperinstallations.clickhouse-keeper.altinity.com
    - clickhouseoperatorconfigurations.clickhouse.altinity.com
    - opentelemetrycollectors.opentelemetry.io
    - opampbridges.opentelemetry.io
    - instrumentations.opentelemetry.io
    - targetallocators.opentelemetry.io

- name: Remove non-namespaced resources
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: "{{ item.api_version }}"
    name: "{{ item.name }}"
    kind: "{{ item.kind }}"
    state: absent
    wait: true
  loop:
    - api_version: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      name: "{{ opentelemetry_operator_collector_kubernetes_events_name }}-collector"
    - api_version: rbac.authorization.k8s.io/v1
      kind: ClusterRole
      name: "{{ opentelemetry_operator_collector_kubernetes_events_name }}-collector"

- name: Uninstall observability tools
  kubernetes.core.helm:
    kubeconfig_path: "{{ kubeconfig }}"
    release_name: "{{ item.name }}"
    release_namespace: "{{ item.namespace }}"
    state: absent
    wait: true
  loop: "{{ observability_releases }}"

- name: Delete associated namespaces
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ item.namespace }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
  loop: "{{ observability_releases }}"

- name: Delete additional namespaces
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ item }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
  loop:
    - "{{ opentelemetry_operator_collectors_namespace }}"
