---
- name: Uninstall the Prometheus stack
  kubernetes.core.helm:
    name: "{{ prometheus_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ prometheus_namespace_project_name }}"
    state: absent
    wait: true

- name: Remove the namespace associated with Prometheus
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ prometheus_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
