---
- name: Uninstall Elasticsearch
  kubernetes.core.helm:
    name: "{{ es_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ es_namespace_project_name }}"
    state: absent
    wait: true

- name: Remove the namespace associated with Elasticsearch
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ es_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
