---
- name: Uninstall OpenCost
  kubernetes.core.helm:
    name: "{{ opencost_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ opencost_namespace_project_name }}"
    state: absent
    wait: true

- name: Remove the namespace associated with OpenCost
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ opencost_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
