---
- name: Uninstall OpenTelemetry Collector for Kubernetes Events
  kubernetes.core.helm:
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    release_name: "{{ helm_releases.collectors.names.kubernetes_events }}"
    release_namespace: "{{ helm_releases.collectors.namespace }}"
    release_state: absent
    wait: true
  when:
    - observability_tools_enabled.stack.opentelemetry

- name: Retrieve all collector instances in the release namespace
  kubernetes.core.k8s_info:
    api_version: opentelemetry.io/v1beta1
    kind: OpenTelemetryCollector
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    namespace: "{{ helm_releases.collectors.namespace }}"
  register: opentelemetry_collector_info
  when:
    - observability_tools_enabled.stack.jaeger

- name: Delete all collector instances in the release namespace
  kubernetes.core.k8s:
    api_version: opentelemetry.io/v1beta1
    delete_all: true
    kind: OpenTelemetryCollector
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    namespace: "{{ helm_releases.collectors.namespace }}"
    state: absent
    wait: true
  when:
    - observability_tools_enabled.stack.jaeger
    - opentelemetry_collector_info.resources | length > 0

- name: Uninstall OpenTelemetry Operator
  kubernetes.core.helm:
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    release_name: "{{ helm_releases.operator.name }}"
    release_namespace: "{{ helm_releases.operator.namespace }}"
    release_state: absent
    wait: true
  when:
    - observability_tools_enabled.stack.jaeger

- name: Delete the release namespaces
  kubernetes.core.k8s:
    kubeconfig: "{{ observability_tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ item }}"
    state: absent
    wait: true
  loop:
    - "{{ helm_releases.collectors.namespace }}"
    - "{{ helm_releases.operator.namespace }}"
