---
- name: Uninstall Ingress
  kubernetes.core.helm:
    name: "{{ ingress_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ ingress_namespace_project_name }}"
    state: absent
    wait: true

- name: Remove the namespace associated with Ingress
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ ingress_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
