---
- name: Deploy non compliant resources
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    namespace: "{{ target_ns }}"
    src: "../manifests/application.yaml"
- name: Deploy Policies
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: present
    namespace: "{{ target_ns }}"
    src: "../manifests/existing-policy.yaml"
