---
- name: Delete the non compliant pods
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    state: absent
    namespace: "{{ target_ns }}"
    src: "../manifests/application.yaml"
- name: Delete all Policies/ClusterPolicies
  command: kubectl delete policy,clusterpolicy --all --kubeconfig="{{ kubeconfig }}"
