---
- name: Documenting Incident #27
  set_fact:
    all_incidents: "{{ all_incidents + [ docs_incident_27 ] }}"
  tags: documentation, incident_27

- name: fault_injection_incident_27
  ansible.builtin.import_role:
    name: fault_injection
  vars:
      is_injection: true
      is_http_abort_chaos: true
      is_install_chaos_mesh: true
  tags: incident_27
  when: is_fault_injection | bool

- name: fault_removal_incident_27
  ansible.builtin.import_role:
    name: fault_injection
  vars:
      is_http_abort_chaos: true
      is_removal: true
      is_install_chaos_mesh: false
  tags: incident_27
  when: is_fault_removal | bool
