- name: Enable X11 forwarding in SSH configuration
  ansible.builtin.lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^X11Forwarding'
    line: 'X11Forwarding yes'
    state: present

- name: Restart SSH service to apply changes
  ansible.builtin.service:
    name: sshd
    state: restarted
