---
- name: Export the kubeconfig
  ansible.builtin.command:
    argv:
      - kops
      - export
      - --name
      - "{{ cluster_name }}"
      - kubecfg
      - --admin
      - --state
      - "{{ state_store }}"
      - --kubeconfig
      - "{{ kubeconfig_path }}"
  register: export_kops_output
  changed_when: export_kops_output.rc == 0

- name: Display file path of kubeconfig
  ansible.builtin.debug:
    msg:
      - 'The kubeconfig has been exported to: {{ kubeconfig_path }}'
      - 'Run the following command to execute kubectl commands:'
      - export KUBECONFIG={{ kubeconfig_path }}
