---
- name: Set variables
  ansible.builtin.set_fact:
    cluster_name: "{{ cluster.name_prefix }}-{{ cluster.nodes.worker.instance_type }}-aws.k8s.local"
    state_store: s3://{{ cluster.s3.bucket_name }}
  tags:
    - always

- name: Override cluster name
  ansible.builtin.set_fact:
    cluster_name: "{{ full_cluster_name_override }}"
  tags:
    - always
  when:
    - full_cluster_name_override is defined

- name: Import KOps cluster creation tasks
  ansible.builtin.import_tasks:
    file: create.yaml
  tags:
    - create

- name: Import KOps cluster list tasks
  ansible.builtin.import_tasks:
    file: list.yaml
  tags:
    - list

- name: Import KOps cluster export tasks
  ansible.builtin.import_tasks:
    file: export.yaml
  tags:
    - export

- name: Import KOps cluster deletion tasks
  ansible.builtin.import_tasks:
    file: delete.yaml
  tags:
    - delete
