---
- name: Set variables
  ansible.builtin.set_fact:
    cluster_name: "{{ kops_cluster.name_prefix }}-{{ kops_cluster.nodes.worker.instance_type }}-aws.k8s.local"
    state_store: s3://{{ kops_cluster.s3.bucket_name }}
  tags:
    - always

- name: Override cluster name
  ansible.builtin.set_fact:
    cluster_name: "{{ kops_full_cluster_name_override }}"
  tags:
    - always
  when:
    - kops_full_cluster_name_override is defined

- name: Import KOps cluster creation tasks
  ansible.builtin.import_tasks:
    file: create.yaml
  tags:
    - create

- name: Import KOps cluster list tasks
  ansible.builtin.import_tasks:
    file: list.yaml
  tags:
    - list

- name: Import KOps cluster export tasks
  ansible.builtin.import_tasks:
    file: export.yaml
  tags:
    - export

- name: Import KOps cluster deletion tasks
  ansible.builtin.import_tasks:
    file: delete.yaml
  tags:
    - delete
