---
- name: Creating bucket if it doesn't exist
  amazon.aws.s3_bucket:
    name: "{{ cluster.s3.bucket_name }}"
    region: "{{ cluster.aws.region }}"
    state: present

- name: Check if the public SSH key file path is set (on creating clusters)
  ansible.builtin.stat:
    path: "{{ cluster.ssh.public_key_path }}"
  register: ssh_public_key_file_path

- name: Check if the private SSH key file path is valid
  ansible.builtin.assert:
    that:
      - ssh_public_key_file_path.stat.exists
      - ssh_public_key_file_path.stat.isreg
      - ssh_public_key_file_path.stat.size > 0
    fail_msg: "Public SSH key file path is missing. Please check the value associated with cluster.ssh.public_key_path at group_vars/development/kops_cluster.yaml."
    success_msg: "Public SSH key file path is set."
