---
- name: Get the Ingress URL of Prometheus
  ansible.builtin.shell: "KUBECONFIG={{ kubeconfig }} kubectl get ingress prometheus -n {{ tools_helm_releases.prometheus.namespace }} -o json"
  register: prometheus_ingress
  retries: 5
  delay: 60
  until: (prometheus_ingress.stdout | length) > 0
  ignore_errors: yes

- name: Extract the Ingress hostname information
  set_fact:
    ingress_hostname: "{{ prometheus_ingress.stdout | from_json | json_query('status.loadBalancer.ingress[0].hostname') }}"
  when: prometheus_ingress.stdout | trim != ''

- name: Set the Prometheus URL
  set_fact:
    prometheus_url: "http://{{ ingress_hostname }}/prometheus"
  when: ingress_hostname is defined and ingress_hostname | trim != ''
