---
- name: Set up main machine
  hosts: localhost
  gather_facts: true
  vars_files:
    - variables.yaml
  tasks:
    # Determine the shell being used
    - name: Determine shell
      command: echo $SHELL
      register: shell_type
      changed_when: False

    - name: Set shell fact
      set_fact:
        user_shell: "{{ shell_type.stdout | regex_replace('.*/', '') }}"

    - name: Install AWS CLI using snap (Ubuntu)
      command: snap install aws-cli --classic
      when: ansible_distribution == 'Ubuntu'
      become: true
    
    - name: Install AWS CLI (Fedora / CentOS / RHEL)
      dnf:
        name: awscli
        state: present
      when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      become: true

    - name: Install AWS CLI (macOS)
      homebrew:
        name: awscli
        state: present
      when: ansible_distribution == 'MacOSX'

    - name: Install curl (Ubuntu)
      apt:
        name: curl
        state: present
      when: ansible_distribution == 'Ubuntu'
      become: true

    - name: Install curl (Fedora / CentOS / RHEL)
      dnf:
        name: curl
        state: present
      when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      become: true

    - name: Install jq (Ubuntu)
      apt:
        name: jq
        state: present
      when: ansible_distribution == 'Ubuntu'
      become: true

    - name: Install jq (Fedora / CentOS / RHEL)
      dnf:
        name: jq
        state: present
      when: ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      become: true

    # kops and kubectl downloads remain the same
    - name: Download kops (Linux)
      get_url:
        url: "https://github.com/kubernetes/kops/releases/download/{{ kops_version }}/kops-linux-amd64"
        dest: "./kops"
        mode: '0755'
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Move kops to /usr/local/bin (Linux)
      command: mv ./kops /usr/local/bin/
      become: yes
      become_user: root
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    # Install kops using brew (macOS)
    - name: Install kops (macOS)
      homebrew:
        name: kops
        state: present
      when: ansible_distribution == 'MacOSX'

    # Download and move kubectl (Fedora)
    - name: Download kubectl (Fedora / CentOS / RHEL)
      get_url:
        url: "https://dl.k8s.io/release/{{ kubectl_version }}/bin/linux/amd64/kubectl"
        dest: "./kubectl"
        mode: '0755'
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Move kubectl to /usr/local/bin (Fedora / CentOS / RHEL)
      command: mv ./kubectl /usr/local/bin/
      become: yes
      become_user: root
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'
      become: true

    # Install kubectl using brew (macOS)
    - name: Install kubectl (macOS)
      homebrew:
        name: kubectl
        state: present
      when: ansible_distribution == 'MacOSX'
