- name: List all kops clusters
  hosts: localhost
  vars_files:
    - variables.yaml
    - secret.yaml
  tasks:
    - name: Set kops path for Linux
      set_fact:
        kops_path: "/usr/local/bin/kops"
      when: ansible_distribution == 'Ubuntu' or ansible_distribution == 'Fedora' or ansible_distribution == 'CentOS' or ansible_distribution == 'RedHat'

    - name: Set kops path for macOS
      set_fact:
        kops_path: "{{ '/opt/homebrew/bin/kops' if ansible_architecture == 'arm64' else '/usr/local/bin/kops' }}"
      when: ansible_distribution == 'MacOSX'

    - name: Run kops get clusters to list all clusters
      command:
        cmd: "{{ kops_path }} get clusters --state s3://{{ s3name}} "
      register: clusters_output

    - name: Format clusters output
      set_fact:
        formatted_lines: '{{ clusters_output.stdout.split("\n") }}'
      register: formatted_output

    - name: Format as table
      ansible.builtin.shell: |
        echo "{{ formatted_lines | join('\n') }}" | column -t
      register: formatted_output

    - name: Parse out cluster names from formatted table
      set_fact:
        known_clusters: "{{ (known_clusters | default([])) + [item.split()[0]] }}"
      loop: "{{ formatted_output.stdout_lines }}"
      when: not item.startswith("NAME ")

    - name: Show all clusters in formatted table
      debug:
        msg: "{{ formatted_output.stdout_lines }}"
