---
- name: kOps (Kubernetes Operations) Cluster Management
  hosts:
    - development
  pre_tasks:
    - name: Import kOps role validation tasks
      ansible.builtin.import_role:
        name: kops
        tasks_from: validate
      vars:
        kops_cluster: "{{ cluster }}"
      tags:
        - always
    - name: Import kOps role validation tasks
      ansible.builtin.import_role:
        name: kops
        tasks_from: pre_tasks_list
      vars:
        kops_cluster: "{{ cluster }}"
      tags:
        - list
    - name: Import kOps role validation tasks
      ansible.builtin.import_role:
        name: kops
        tasks_from: pre_tasks_create
      vars:
        kops_cluster: "{{ cluster }}"
      tags:
        - create
  tasks:
    - name: Import kOps role
      ansible.builtin.import_role:
        name: kops
      vars:
        kops_cluster: "{{ cluster }}"
