---
- name: KOps (Kubernetes Operations) Cluster Management
  hosts:
    - development
  pre_tasks:
    - name: Import KOps role validation tasks
      ansible.builtin.import_role:
        name: kops
        tasks_from: validate
      vars:
        kops_cluster: "{{ cluster }}"
      tags:
        - always
  tasks:
    - name: Creating bucket if it doesn't exist
      amazon.aws.s3_bucket:
        name: "{{ cluster.s3.bucket_name }}"
        region: "{{ cluster.aws.region }}"
        state: present
      tags:
        - create

    - name: Import KOps role
      ansible.builtin.import_role:
        name: kops
      vars:
        kops_cluster: "{{ cluster }}"
