---
observability_tools_helm_releases:
  clickhouse:
    name: clickhouse
    namespace: clickhouse
  clickhouse_operator:
    name: clickhouse-operator
    namespace: clickhouse-operator
  ingress:
    name: ingress-nginx
    namespace: ingress-nginx
  kubernetes_topology_monitor:
    name: topology-monitor
    namespace: kube-system
  opencost:
    name: opencost
    namespace: opencost
  opensearch:
    name: opensearch
    namespace: opensearch
  opentelemetry_collectors:
    names:
      kubernetes_events: kubenetes-events
    namespace: opentelemetry-collectors
  opentelemetry_operator:
    name: opentelemetry-operator
    namespace: opentelemetry-operator
  prometheus:
    name: prometheus
    namespace: prometheus
