---
- name: Uninstall the Kubernetes topology mapper
  kubernetes.core.helm:
    name: "{{ topology_mapper_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ topology_mapper_namespace_project_name }}"
    state: absent
    wait: true
  tags:
    - pre_fault_removal
