---
- name: Uninstall the Kubernetes topology mapper
  kubernetes.core.helm:
    name: "{{ tools_helm_releases.kubernetes_topology_monitor.name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ tools_helm_releases.kubernetes_topology_monitor.namespace }}"
    state: absent
    wait: true
  tags:
    - pre_fault_removal
