---
apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: cluster-alerting-rules
spec:
  groups:
    - name: ClusterAlerts
      interval: 1m
      rules:
        - alert: FailedPodsDetected
          expr: sum by(namespace) (kube_pod_status_phase{phase="Failed"}) > 0
          labels:
            severity: critical
          annotations:
            description: 'Pods in failed state in namespace {{ $labels.namespace }} is above 0 (current value: {{ $value }})'
        - alert: PendingPodsDetected
          expr: sum by(namespace) (kube_pod_status_phase{phase="Pending"}) > 0
          labels:
            severity: critical
          annotations:
            description: 'Pods in pending state in namespace {{ $labels.namespace }} above 0 (current value: {{ $value }})'
