- name: Import tools role
  ansible.builtin.import_role:
    name: tools
  vars:
    tools_cluster:
      cloud_provider: "{{ cluster_provider }}"
      kubeconfig: "{{ cluster.kubeconfig }}"
      platform: "{{ cluster_platform }}"
    tools_enabled:
      chaos_mesh: "{{ tools.chaos_mesh | default(false) }}"
      clickhouse: "{{ tools.clickhouse | default(false) }}"
      ingress: "{{ tools.ingress | default(false) }}"
      jaeger: "{{ tools.jaeger | default(false) }}"
      kubernetes_metrics_server: "{{ tools.kubernetes_metrics_server | default(false) }}"
      kubernetes_topology_monitor: "{{ tools.kubernetes_topology_monitor | default(false) }}"
      opencost: "{{ tools.opencost | default(false) }}"
      opensearch: "{{ tools.opensearch | default(false) }}"
      opentelemetry: "{{ tools.opentelemetry | default(false) }}"
      prometheus: "{{ tools.prometheus | default(false) }}"

- name: Import applications role
  ansible.builtin.import_role:
    name: applications
  vars:
    tools_cluster:
      cloud_provider: "{{ cluster_provider }}"
      kubeconfig: "{{ cluster.kubeconfig }}"
      platform: "{{ cluster_platform }}"
    tools_enabled:
      chaos_mesh: "{{ tools.chaos_mesh | default(false) }}"
      clickhouse: "{{ tools.clickhouse | default(false) }}"
      ingress: "{{ tools.ingress | default(false) }}"
      jaeger: "{{ tools.jaeger | default(false) }}"
      kubernetes_metrics_server: "{{ tools.kubernetes_metrics_server | default(false) }}"
      kubernetes_topology_monitor: "{{ tools.kubernetes_topology_monitor | default(false) }}"
      opencost: "{{ tools.opencost | default(false) }}"
      opensearch: "{{ tools.opensearch | default(false) }}"
      opentelemetry: "{{ tools.opentelemetry | default(false) }}"
      prometheus: "{{ tools.prometheus | default(false) }}"

- name: Import environment role
  ansible.builtin.import_role:
    name: environment
  vars:
    tools_cluster:
      cloud_provider: "{{ cluster_provider }}"
      kubeconfig: "{{ cluster.kubeconfig }}"
      platform: "{{ cluster_platform }}"
    tools_enabled:
      chaos_mesh: "{{ tools.chaos_mesh | default(false) }}"
      clickhouse: "{{ tools.clickhouse | default(false) }}"
      ingress: "{{ tools.ingress | default(false) }}"
      jaeger: "{{ tools.jaeger | default(false) }}"
      kubernetes_metrics_server: "{{ tools.kubernetes_metrics_server | default(false) }}"
      kubernetes_topology_monitor: "{{ tools.kubernetes_topology_monitor | default(false) }}"
      opencost: "{{ tools.opencost | default(false) }}"
      opensearch: "{{ tools.opensearch | default(false) }}"
      opentelemetry: "{{ tools.opentelemetry | default(false) }}"
      prometheus: "{{ tools.prometheus | default(false) }}"

- name: Import faults role
  ansible.builtin.import_role:
    name: faults
  vars:
    tools_cluster:
      cloud_provider: "{{ cluster_provider }}"
      kubeconfig: "{{ cluster.kubeconfig }}"
      platform: "{{ cluster_platform }}"
    tools_enabled:
      chaos_mesh: "{{ tools.chaos_mesh | default(false) }}"
      clickhouse: "{{ tools.clickhouse | default(false) }}"
      ingress: "{{ tools.ingress | default(false) }}"
      jaeger: "{{ tools.jaeger | default(false) }}"
      kubernetes_metrics_server: "{{ tools.kubernetes_metrics_server | default(false) }}"
      kubernetes_topology_monitor: "{{ tools.kubernetes_topology_monitor | default(false) }}"
      opencost: "{{ tools.opencost | default(false) }}"
      opensearch: "{{ tools.opensearch | default(false) }}"
      opentelemetry: "{{ tools.opentelemetry | default(false) }}"
      prometheus: "{{ tools.prometheus | default(false) }}"
