---
- name: Install sample applications
  ansible.builtin.import_tasks:
    file: install_applications.yaml
  tags:
    - install_applications

- name: Register application deployment time
  ansible.builtin.import_tasks:
    file: register_deployment_time.yaml
  tags:
    - install_applications

- name: Record failed deployment
  ansible.builtin.import_tasks:
    file: register_deployment_failure.yaml
  tags:
    - capture_failed_deployment_state
  when:
    - sre_bench_runner

- name: Uninstall sample applications
  ansible.builtin.import_tasks:
    file: uninstall_applications.yaml
  tags:
    - uninstall_applications
