---
- name: Set deployment time
  ansible.builtin.set_fact:
    deployment_timestamp: "{{ now(utc=True, fmt='%Y-%m-%dT%H:%M:%SZ') }}"

- name: Create application namespace map
  ansible.builtin.set_fact:
    namespaces:
      otel_astronomy_shop: "{{ otel_astronomy_app_namespace_project_name }}"
      dsb_hotel_reservation: "{{ deathstarbench_hotelreservation_app_namespace_project_name }}"
      elasticsearch: "{{ elasticsearch_app_namespace_project_name }}"

- name: Record Deployment time
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: bundle-alert-timestamps
    namespace: "{{ namespaces[ {{ item }} ] }}"
    kind: ConfigMap
    apiVersion: v1
    resource_definition:
      data:
        deployment_time: "{{ deployment_timestamp }}"
  loop: "{{ sample_applications }}"

- name: Create deployment record
  ansible.builtin.set_fact:
    assertion_json:
      status:
        conditions:
          - type: Deployed
            status: True
            lastTransitionTime: "{{ deployment_timestamp }}"
  when:
    - sre_bench_runner

- name: Create a JSON with application deployment details
  ansible.builtin.copy:
    content: "{{ assertion_json | to_json | indent(2) }}"
    dest: "/tmp/assertion.json"
    mode: "0644"
  when:
    - sre_bench_runner

- name: Upload the JSON with application deployment details to S3
  amazon.aws.s3_object:
    endpoint_url: "{{ s3_endpoint_url }}"
    bucket: "{{ s3_bucket_name_for_results }}"
    object: "/{{ sre_agent_name__version_number }}/{{run_uuid}}/{{scenario_number}}/{{run_number}}/assertion.json"
    src: "/tmp/assertion.json"
    mode: put
  when:
    - sre_bench_runner
    - run_uuid is defined
    - scenario_number is defined
    - run_number is defined
