---
- name: Remove Prometheus Rules for Alerting
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    namespace: "{{ otel_astronomy_app_namespace_project_name }}"
    state: absent
    src: files/rules/hotel-reservation.yaml

- name: Uninstall / remove OpenTelemetry's Astronomy Shop Demo
  kubernetes.core.helm:
    name: "{{ otel_astronomy_app_installation_name }}"
    kubeconfig_path: "{{ kubeconfig }}"
    release_namespace: "{{ otel_astronomy_app_namespace_project_name }}"
    state: absent
    wait: true

- name: Remove custom Security Context Constraints (SCC) for OTEL's Astronomy Shop on OpenShift
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    api_version: security.openshift.io/v1
    kind: SecurityContextConstraints
    name: otel-astronomy-shop-scc
    state: absent
    wait: true
  when:
    - cluster_type is defined
    - cluster_type == "openshift" or cluster_type == "openshift_crc_local"

- name: Remove the namespace associated with the installation of OpenTelemetry's Astronomy Shop Demo
  kubernetes.core.k8s:
    kubeconfig: "{{ kubeconfig }}"
    name: "{{ otel_astronomy_app_namespace_project_name }}"
    api_version: v1
    kind: Namespace
    state: absent
    wait: true
