---
argument_specs:
  main:
    short_description: Entry point for AWX stack management tasks
    description:
      - This is a collection of validation tasks needed to manage the lifecyle
        of an AWX stack.
    author:
      - Rohan Arora
      - Gerard Vanloo
    options:
      cluster:
        description: The configuration of the cluster
        required: true
        type: dict
      stack:
        description: The configuration of the AWX stack
        required: true
        type: dict
  validate:
    short_description: Entry point for AWX configuration validation tasks
    description:
      - This is a collection of validation tasks needed to run the various other tasks.
      - These tasks include verfying the existence of the KOps cli and the S3 bucket where
        the KOps cluster states will be stored and validating the configuration used in the
        other tasks for managing the various clusters.
      - These tasks should be run as a pre-task in playbooks which invoke this role.
    author:
      - Gerard Vanloo
    options:
      stack:
        required: true
        type: dict
        options:
          name_prefix:
            required: true
            type: str
          runners:
            required: true
            type: dict
            options:
              aws:
                required: true
                type: dict
                options:
                  subnet:
                    required: true
                    type: dict
                    options:
                      public_base:
                        required: true
                        type: str
                  vpc:
                    required: true
                    type: dict
                    options:
                      cidr:
                        required: true
                        type: str
              count:
                required: true
                type: int
