---
- name: Check for the existence of the Service Monitor CRD
  kubernetes.core.k8s_info:
    kubeconfig: "{{ fault_tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: apiextensions.k8s.io/v1
      kind: CustomResourceDefinition
      metadata:
        name: servicemonitors.monitoring.coreos.com
  register: service_monitor_info

- name: Import Chaos Mesh installation tasks
  ansible.builtin.import_tasks:
    file: install_chaos_mesh.yaml
  vars:
    helm_release: "{{ fault_tools_helm_releases.chaos_mesh }}"
  when:
    - fault_tools_enabled.chaos_mesh

- name: Import Kubernetes Metrics Server installation tasks
  ansible.builtin.import_tasks:
    file: install_kubernetes_metrics_server.yaml
  vars:
    helm_release: "{{ fault_tools_helm_releases.kubernetes_metrics_server }}"
  when:
    - fault_tools_enabled.kubernetes.metrics_server
    - fault_tools_cluster.platform == "kubernetes"
