---
- name: Create release namespace
  kubernetes.core.k8s:
    kubeconfig: "{{ fault_tools_cluster.kubeconfig }}"
    resource_definition:
      api_version: v1
      kind: Namespace
      metadata:
        name: "{{ helm_release.namespace }}"
        labels:
          it-bench/monitoring: "true"
    state: present

- name: Install Chaos Mesh
  kubernetes.core.helm:
    chart_ref: chaos-mesh
    chart_repo_url: https://charts.chaos-mesh.org
    chart_version: 2.7.1
    create_namespace: true
    kubeconfig: "{{ fault_tools_cluster.kubeconfig }}"
    release_name: "{{ helm_release.name }}"
    release_namespace: "{{ helm_release.namespace }}"
    release_state: present
    values:
      chaosDaemon:
        runtime: containerd
        socketPath: /run/containerd/containerd.sock
      dnsServer:
        create: false
    wait: true
