---
- name: Import Chaos Mesh installation tasks
  ansible.builtin.import_tasks:
    file: install_chaos_mesh.yaml
  vars:
    helm_release: "{{ fault_tools_helm_releases.chaos_mesh }}"
  when:
    - fault_tools_enabled.chaos_mesh
