---
- name: Import Chaos Mesh uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_chaos_mesh.yaml
  vars:
    helm_release: "{{ fault_tools_helm_releases.chaos_mesh }}"
  when:
    - fault_tools_enabled.chaos_mesh

- name: Import Kubernetes Metrics Server uninstallation tasks
  ansible.builtin.import_tasks:
    file: uninstall_kubernetes_metrics_server.yaml
  vars:
    helm_release: "{{ fault_tools_helm_releases.kubernetes_metrics_server }}"
  when:
    - fault_tools_enabled.kubernetes_metrics_server
    - fault_tools_cluster.platform == "kubernetes"
