---
- name: Find all JSON files in the specified directory
  ansible.builtin.find:
    paths: "{{ alertsfilepath }}"
    patterns: "*.json"
  register: json_files
  tags:
   - delete_files

- name: Delete all JSON files in the specified directory
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: absent
  loop: "{{ json_files.files }}"
  when: json_files.matched > 0
  tags:
    - delete_files