---
- name: Get the Ingress URL of Grafana
  ansible.builtin.shell: "KUBECONFIG={{ kubeconfig }} kubectl get ingress grafana -n {{ grafana_namespace_project_name }} -o json"
  register: grafana_ingress
  tags:
    - fetch_alerts

- name: Construct the alerts API URI
  set_fact:
    alerts_api_url: "http://{{ grafana_ingress.stdout | from_json | json_query('status.loadBalancer.ingress[0].hostname') }}/{{ grafana_namespace_project_name }}/api/prometheus/grafana/api/v1/alerts"
  tags:
    - fetch_alerts

- name: Get alerts dump for an incident
  command: >
    python3 roles/evaluation/sre_evaluation/alertsdump.py
    --url="{{ alerts_api_url }}"
    --alertsfilepath="{{ alertsfilepath }}" 
    --pollinginterval="{{ pollinginterval }}" 
    --active_alert_wait_time="{{ wait_time }}" 
    --incidentno="{{ incident_number }}"
  when:  alerts_api_url is defined 
  tags:
    - fetch_alerts
