---
argument_specs:
  main:
    short_description: Main entry point for obervability_tools role
    description:
      - This is the main entry point for the obervability_tools role.
      - This role is responsible for installing and uninstalling observability tools and services.
    author:
      - Gerard Vanloo
    options:
      obervability_tools_cluster:
        required: false
        type: dict
        options:
          kubeconfig:
            default: ~/.kube/config
            required: false
            type: str
          platform:
            choices:
              - kubernetes
              - openshift
            default: kubernetes
            required: false
            type: str
      obervability_tools_enabled:
        default:
        required: false
        type: dict
        options:
          stack:
            required: false
            type: dict
            options:
              clickhouse:
                default: false
                required: false
                type: bool
              ingress:
                default: false
                required: false
                type: bool
              jaeger:
                default: false
                required: false
                type: bool
              opencost:
                default: false
                required: false
                type: bool
              opensearch:
                default: false
                required: false
                type: bool
              opentelemetry:
                default: false
                required: false
                type: bool
              prometheus:
                default: false
                required: false
                type: bool
          kubernetes:
            required: false
            type: dict
            options:
              topology_monitor:
                default: false
                required: false
                type: bool
