---
main:
  options:
    tools:
      choices:
        - grafana
        - ingress
        - jaeger
        - kubernetes-event-exporter
        - kubernetes-metric-exporter
        - kubernetes-topology-mapper
        - loki
        - opensearch
        - opencost
        - prometheus
      description: A list of tools to be installed
      elements: str
      required: true
      type: list
