---
- name: Delete all Kyverno Policies
  ansible.builtin.command:
    cmd: "kubectl delete policy --all --kubeconfig {{ kubeconfig }}"

- name: Delete all Kyverno ClusterPolicies
  ansible.builtin.command:
    cmd: "kubectl delete clusterpolicy --all --kubeconfig {{ kubeconfig }}"
