apiVersion: v1
items:
- apiVersion: wgpolicyk8s.io/v1alpha2
  kind: PolicyReport
  metadata:
    creationTimestamp: "2024-11-13T05:32:51Z"
    generation: 1
    labels:
      app.kubernetes.io/managed-by: kyverno
    name: 4bddea03-cff9-4f23-ab84-d0529354ef53
    namespace: paa
    ownerReferences:
    - apiVersion: v1
      kind: Pod
      name: test-untrusted-registry
      uid: 4bddea03-cff9-4f23-ab84-d0529354ef53
    resourceVersion: "64635"
    uid: 35869895-af0b-496e-944d-c539a75a1606
  results:
  - message: validation rule 'require-non-default-service-account' passed.
    policy: service-account-requirements
    result: pass
    rule: require-non-default-service-account
    scored: true
    source: kyverno
    timestamp:
      nanos: 0
      seconds: 1731475961
  - message: validation rule 'disallow-privilege-escalation' passed.
    policy: container-security-controls
    result: pass
    rule: disallow-privilege-escalation
    scored: true
    source: kyverno
    timestamp:
      nanos: 0
      seconds: 1731475961
  scope:
    apiVersion: v1
    kind: Pod
    name: test-untrusted-registry
    namespace: paa
    uid: 4bddea03-cff9-4f23-ab84-d0529354ef53
  summary:
    error: 0
    fail: 0
    pass: 2
    skip: 0
    warn: 0
kind: List
metadata:
  resourceVersion: ""
