name: Perform smoke tests for fault tools

on:
  pull_request:
    branches:
      - main
    paths:
      - sre/manage_tools.yaml
      - sre/roles/fault_tools/*

jobs:
  chaos-mesh:
    name: Chaos Mesh Smoke Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-go@v5
        with:
          go-version-file: sre/local_cluster/go.mod
          cache-dependency-path: sre/local_cluster/go.sum
      - name: Install Helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
      - name: Install Python and Ansible dependencies
        run: |
          pip install -r sre/requirements.txt
          ansible-galaxy install -r sre/requirements.yaml
      - name: Create Kind cluster
        run: |
          make -C sre/local_cluster create_cluster
      - name: Create group vars
        run: |
          make -C sre group_vars
          echo "observability_tools: {}" > sre/group_vars/environment/observability_tools.yaml
          echo "fault_tools: { chaos_mesh: true }" > sre/group_vars/environment/fault_tools.yaml
      - name: Run installation smoke test
        run: |
          make -C sre deploy_environment_tools
      - name: Run uninstallation smoke test
        run: |
          make -C sre undeploy_environment_tools
  kubernetes_metrics_server:
    name: Kubernetes Metrics Server Smoke Tests
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - uses: actions/setup-go@v5
        with:
          go-version-file: sre/local_cluster/go.mod
          cache-dependency-path: sre/local_cluster/go.sum
      - name: Install Helm
        run: |
          curl https://baltocdn.com/helm/signing.asc | gpg --dearmor | sudo tee /usr/share/keyrings/helm.gpg > /dev/null
          sudo apt-get install apt-transport-https --yes
          echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/helm.gpg] https://baltocdn.com/helm/stable/debian/ all main" | sudo tee /etc/apt/sources.list.d/helm-stable-debian.list
          sudo apt-get update
          sudo apt-get install helm
      - name: Install Python and Ansible dependencies
        run: |
          pip install -r sre/requirements.txt
          ansible-galaxy install -r sre/requirements.yaml
      - name: Create Kind cluster
        run: |
          make -C sre/local_cluster create_cluster
      - name: Create group vars
        run: |
          make -C sre group_vars
          echo "observability_tools: {}" > sre/group_vars/environment/observability_tools.yaml
          echo "fault_tools: { kubernetes_metrics_server: true }" > sre/group_vars/environment/fault_tools.yaml
      - name: Run installation smoke test
        run: |
          make -C sre deploy_environment_tools
      - name: Run uninstallation smoke test
        run: |
          make -C sre undeploy_environment_tools
