name: Build and push forked version of DSB apps

on:
  pull_request:
    branches:
      - main
    paths:
      - sre/tools/death-star-bench-*/*

jobs:
  # hotel-reservation:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout fork of DSB Hotel Reservation
  #       uses: actions/checkout@v4
  #       with:
  #         path: deathstarbench
  #         repository: it-bench/DeathStarBench
  #         sparse-checkout: hotelReservation
  #     - name: Checkout Dockerfile
  #       uses: actions/checkout@v4
  #       with:
  #         path: main
  #         sparse-checkout: sre/tools/death-star-bench-hotel-reservation
  #     - name: Login to Quay.io
  #       uses: docker/login-action@v3
  #       with:
  #         registry: quay.io
  #         username: ${{ secrets.QUAY_USERNAME }}
  #         password: ${{ secrets.QUAY_ROBOT_TOKEN }}
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Build and push Hotel Reservation
  #       uses: docker/build-push-action@v6
  #       env:
  #         DOCKER_BUILD_RECORD_UPLOAD: false
  #       with:
  #         context: deathstarbench/hotelReservation
  #         file: main/sre/tools/death-star-bench-hotel-reservation/Dockerfile
  #         platforms: |
  #           linux/amd64
  #           linux/arm64
  #         push: true
  #         tags: |
  #           quay.io/it-bench/dsb-hotel-reservation:0.0.3
  #           quay.io/it-bench/dsb-hotel-reservation:latest
  wrk2:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout fork of DSB wrk2
        uses: actions/checkout@v4
        with:
          path: deathstarbench
          repository: it-bench/DeathStarBench
          sparse-checkout: wrk2
          submodules: true
      - name: Checkout Dockerfile
        uses: actions/checkout@v4
        with:
          path: main
          sparse-checkout: sre/tools/death-star-bench-wrk2-load-generator
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push wrk2 load generator
        uses: docker/build-push-action@v6
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: deathstarbench/wrk2
          file: main/sre/tools/death-star-bench-wrk2-load-generator/Dockerfile
          platforms: |
            linux/amd64
          push: true
          tags: |
            quay.io/it-bench/dsb-wrk2-load-generator:0.0.3
            quay.io/it-bench/dsb-wrk2-load-generator:latest
