name: Build and push SRE tool images

on:
  push:
    branches:
      - main
    paths:
      - sre/tools/kubernetes-topology-mapper/*
      - sre/tools/astronomy-shop-checkout-service/*

jobs:
  topology-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4.2.2
      - name: Login to Quay.io
        uses: docker/login-action@v3.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Build and push Kubernetes Topology Mapper
        uses: docker/build-push-action@v6.18.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: sre/tools/kubernetes-topology-mapper
          platforms: |
            linux/amd64
            linux/arm64
          push: true
          tags: |
            quay.io/it-bench/topology-monitor:0.0.3
            quay.io/it-bench/topology-monitor:latest
  unsupported-checkout-service:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v4.2.2
      - name: Login to Quay.io
        uses: docker/login-action@v3.4.0
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3.6.0
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.10.0
      - name: Build and push Unsupported Astronomy Shop Checkout Service image (amd)
        uses: docker/build-push-action@v6.18.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: sre/tools/astronomy-shop-checkout-service
          platforms: |
            linux/amd64
          push: true
          tags: |
            quay.io/it-bench/unsupported-checkout-service-amd64:0.0.3
            quay.io/it-bench/unsupported-checkout-service-amd64:latest
      - name: Build and push Unsupported Astronomy Shop Checkout Service image (arm)
        uses: docker/build-push-action@v6.18.0
        env:
          DOCKER_BUILD_RECORD_UPLOAD: false
        with:
          context: sre/tools/astronomy-shop-checkout-service
          platforms: |
            linux/arm64
          push: true
          tags: |
            quay.io/it-bench/unsupported-checkout-service-arm64:0.0.3
            quay.io/it-bench/unsupported-checkout-service-arm64:latest
