name: Lint SRE remote cluster playbooks

on:
  pull_request:
    branches:
      - main
    paths:
      - sre/remote_cluster/playbooks/*
      - sre/remote_cluster/roles/*

jobs:
  lint:
    name: Lint remote cluster playbooks
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Run ansible-lint
        uses: ansible/ansible-lint@v25
        with:
          args:
            - playbooks/manage_awx_stack.yaml
            - playbooks/manage_kops_cluster.yaml
            - roles/awx
            - roles/kops
          working_directory: sre/remote_cluster
          requirements_file: ../requirements.yaml
