name: ci

on:
  push:
    branches:
      - main
    paths:
      - sre/tools/kubernetes-topology-mapper/*

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Login to Quay.io
        uses: docker/login-action@v3
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: sre/tools/kubernetes-topology-mapper
          push: true
          tags:
            - it-bench/topology-monitor:0.0.1
            - it-bench/topology-monitor:latest
